### PR TITLE
fix(balancer) proper IPv6 format for set_current_peer()

### PR DESCRIPTION
**Pull request by thibaultcha**
`ngx.set_current_peer()` expects IPv6 to be specified in square brackets
notation, or else it will interpret an IP as an IPv6, causing a "invalid
port while connecting to upstream" error from NGINX.

This is a first step (without tests, and with improvable
maintainability) towards supporting IPv6 in Targets.

This fix goes in hand with support for square brackets notation in the
lua-resty-dns-client library, for which a fix exists at:

  Kong/lua-resty-dns-client#f93b84e8c146ee263462f0619f7bb03e2cb6cb4a

### CODE REVIEW

**Comment by Tieske** [comment]
I don't think we need this. Every hostname/ip is being looked up by the dns-client. When a dns lookup is done for an IP address, the client will simply detect that the first time, create a fake record in the cache (either A or AAAA depending on the type), with a ttl of 10 years.
From this point onwards, every next access is just a cache lookup.

So if we, upon insertion in the dns-cache, make sure the IPv6 is in the right format, then everything else will be automatically dealt with. So whether you specify an ipv6 with or without brackets, the final address set will always be with brackets.

Besides that I think `utils.normalize_ip()` should return the IPv6 in brackets.

**Comment by thibaultcha** [comment]
> Besides that I think utils.normalize_ip() should return the IPv6 in brackets.

Yes, but this isn't done here because it could break a lot of existing code.

**Comment by thibaultcha** [comment]
@Tieske Have you tried using the fix at lua-resty-dns-client without this fix to the balancer?

**Comment by Tieske** [comment]
No, the current fix of the dns-client does not include my proposed solution above yet.

**Comment by thibaultcha** [comment]
@Tieske Sounds good!

**Comment by Tieske** [comment]
I updated https://github.com/Kong/lua-resty-dns-client/pull/29 such that now all IPv6 addresses will be returned in brackets.

There is one thing I'm not confident about: when requesting an IP from the balancer, it will return ip+port+hostname. The hostname is the name to be set as the upstream host header. It is simply the hostname fed into the balancer through `balancer:addHost()`. The balancer will only use it as a key, but won't do anything with it (the dns resolution done will work with or without brackets).

So if any specific format is required for the returned hostname, then it's up to Kong to provide that format when adding hosts. This requires adding some Kong integration tests to prove correct behaviour imo.

**Comment by hishamhm** [comment]
Adding some data points: 

Reporting that, with https://github.com/Kong/lua-resty-dns-client/pull/29 (and without this PR), I was able to run the `spec/02-integration/05-proxy/09-balancer_spec.lua` test suite using `[0000:0000:0000:0000:0000:0000:0000:0001]` as localhost. Adding https://github.com/Kong/kong/pull/3090, I was also able to run it with `::1` as localhost.

**Comment by hishamhm** [comment]
Also, note that the schema for `targets` runs both `normalize_ip` and `format_host` and the latter _does_ insert the brackets. So if IPs returns by the DNS library always returns the brackets and the DAO ensures they'll be always present, it seems to me we're now safe on both ends (with updated dns-client) and it's then not necessary to manually add them in the balancer module as per this PR?

**Comment by thibaultcha** [comment]
This is a good place for this discussion and an ice-breaker, but not a definitive fix. I'm happy if we decide to fix it at a lower level (in the library and model layer). I'll be closing it now that work has been done here and in the dns-client library!

**Comment by chobits** [comment]
The underlying function `ngx_parse_url()` called by `balancer.set_curret_peer()` does not support IPv6 address without `[]` included:

https://github.com/nginx/nginx/blob/f255815f5d161fab0dd310fe826d4f7572e141f2/src/core/ngx_inet.c#L696

**Pull request closed without merging**
