### PR TITLE
feat(plugin/response-transformer): added support for json_body rename

### PR DESCRIPTION
**Pull request by zhongweikang**
### Summary

detail here: https://github.com/Kong/kong/discussions/12824.

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### CODE REVIEW

**Comment by zhongweikang** [comment]
Sorry, I don't know how to fix the following error from busted. I trying to figure it out but I've made no progress.

```
FAIL spec/02-integration/02-cmd/10-migrations_spec.lua:129: kong migrations #off bootstrap always reports as bootstrapped
spec/02-integration/02-cmd/10-migrations_spec.lua:131: Expected objects to be the same.
Passed in:
(number) 1
Expected:
(number) 0
```

**Comment by zhongweikang** [comment]
Hey @bungle. Can you help me approval this workflow?
I added new fields to removed_fields.lua and added a test for this.
Thank you so much.

**Comment by zhongweikang** [comment]
Hey @chronolaw, I read the error logs of the test runner, but I didn't find anything related to my changes. could you help me with that?

**Comment by chronolaw** [comment]
> Hey @chronolaw, I read the error logs of the test runner, but I didn't find anything related to my changes. could you help me with that?

Some test cases are flaky, rerun the tests can make them green.

**Comment by zhongweikang** [comment]
@samugi @jschmid1  could you help to take a look at this PR?

**Review by jschmid1 — APPROVED** [review]

**Comment by samugi** [comment]
closing was unintentional! I intended to resolve conflicts but the force-push resulted in the PR to auto-close

**Comment by samugi** [comment]
closing was unintentional! I intended to resolve conflicts but the force-push resulted in the PR to auto-close

**Comment by zhongweikang** [comment]
> closing was unintentional! I intended to resolve conflicts but the force-push resulted in the PR to auto-close

So I should start a new PR？

**Comment by samugi** [comment]
@zhongweikang reopened here: https://github.com/Kong/kong/pull/13131
so sorry about my mistake :( and thank you for the contribution!

**Pull request closed without merging**
