### PR TITLE
Merge branch 'master' into next

### PR DESCRIPTION
**Pull request by hishamhm**
Not sure if this will merge the way we want, or if it will make a double `merge` commit

### CODE REVIEW

**Comment by thibaultcha** [comment]
It seems like the CI is failing due to some missing updates to the AWS Lambda tests about the new migrations in next.

**Comment by hishamhm** [comment]
@thibaultcha it's green now. Do we attempt merging this?

**Comment by thibaultcha** [comment]
@hishamhm Absolutely! I believe that a "rebase and merge" would result in the equivalent of a direct push from a local merge (with only the "Merge branch 'master' into next" commit showing up in the next branch).

**Comment by hishamhm** [comment]
What, _now_ it started complaining due to conflicts :confounded:

**Comment by hishamhm** [comment]
and _without_ a list of conflicting files!

**Comment by hishamhm** [comment]
@thibaultcha oh, "Rebase and merge" is blocked, but the "Create a merge commit" option is available. Do we shrug and go with that?

**Comment by hishamhm** [comment]
If Github's command line instructions are to be believed as the equivalent of what the green button would do, the "Merge pull request" option will indeed create a double merge commit entry (because of its `--no-ff` option).

**Comment by hishamhm** [comment]
Merging manually without `--no-ff` worked!

**Pull request merged**
