### PR TITLE
docs(changelog) correct contributor name

### PR DESCRIPTION
**Pull request by hbagdi**
Correct contributor hbagdi's handle from hbadgi to hbagdi

### CODE REVIEW

**Comment by hbagdi** [comment]
This is a very minor change and may be doesn't need a commit...

**Comment by thibaultcha** [comment]
Apologies! That's my bad.

**Comment by hbagdi** [comment]
@thibaultcha happens quite often with me. No problem!

**Comment by thibaultcha** [comment]
@hbagdi Same with mine 😀

**Pull request merged**
