### PR TITLE
Move kong build tools version to .requirements file

### PR DESCRIPTION
**Pull request by eskerda**
### Summary

Move kong build tools version to .requirements file.

Since more tools depend on kong build tools being pinned somewhere, it's easier to grep on the `.requirements` file than hardcoded on  the Makefile

### Full changelog

* Move kong build tools version as KONG_BUILD_TOOLS_VERSION in `.requirements` file

### CODE REVIEW

**Comment by dndx** [comment]
@eskerda Since the RC1 build for 2.1.0 is out and we want to avoid making changes to the release branch at this point if possible. Should we consider merge this onto `next` instead?

**Comment by bungle** [comment]
@eskerda, could you please rebase this to `next`, and I'll merge it then.

**Comment by eskerda** [comment]
@bungle rebased!

**Comment by eskerda** [comment]
Rebased again...

**Pull request merged**
