### PR TITLE
perf(balancer): reduce table resizes and table creation

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Reduces table creation and table resizes on balancer by utilizing a tablepool.

### CODE REVIEW

**Comment by hbagdi** [comment]
@bungle Is this still being persued or are we dropping this one?

**Comment by ADD-SP** [comment]
@bungle Is this PR already in progress?

**Comment by kikito** [comment]
@bungle please rebase this one

@locao assigning this to you for review. Thanks!

**Comment by dndx** [comment]
@bungle Could you resolve the conflicts on this PR?

**Comment by bungle** [comment]
@hbagdi yes, I am still looking if this has any benefits.

**Pull request closed without merging**
