### PR TITLE
Fix spelling in `lua` and `t` files

### PR DESCRIPTION
**Pull request by jbampton**
### Summary

 
Fixes some typos

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Review by bungle — APPROVED** [review]

**Review by bungle — CHANGES_REQUESTED** [review]
Seems like the cert itself has a typo. So to get test green we need to update the certs too.

**Comment by jbampton** [comment]
Hey @bungle could you please explain further ?

I am not sure where to make the change

**Comment by bungle** [comment]
> Hey @bungle could you please explain further ?
> 
> I am not sure where to make the change

The `Kong Testing Intermidiate CA` comes from:
https://github.com/Kong/kong/blob/master/t/certs/intermediate.crt

To fix that you need to generate new intermediate.crt that does not contain this typo.

**Comment by hbagdi** [comment]
Closing because stale

**Pull request closed without merging**
