### PR TITLE
fix(router): always calculate `match_t.upstream_uri` to avoid wrong cache

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

KAG-3505

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Review by windmgc — APPROVED** [review]
LGTM

**Comment by windmgc** [comment]
I'm also a bit concerned that after the change, those string manipulations are executed on every request, which may cause additional resource usage and we may need a proper performance test to check the exact influence level. 
But it may not be a great one since I don't see any expensive operation in it

**Comment by chronolaw** [comment]
> I'm also a bit concerned that after the change, those string manipulations are executed on every request, which may cause additional resource usage and we may need a proper performance test to check the exact influence level. But it may not be a great one since I don't see any expensive operation in it

Sure, because now we do not cache `upstream_uri`, we have to calculate it in each request.
If we add `req_uri` in cache_key then we will erase this cost.

**Review by ADD-SP — APPROVED** [review]

**Review by dndx — APPROVED** [review]

**Review by dndx — APPROVED** [review]

**Comment by dndx** [comment]
@chronolaw Approved, notice that this should be a `fix`, not `refactor`.

**Pull request merged**
