### PR TITLE
tests(helpers): separate server mock functions

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

KAG-5254

### Checklist

- [ ] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Comment by Tieske** [comment]
please validate that the documentation still renders properly when changing those helper files.

```
cd spec
ldoc .
```

should render the docs properly. Users access this through `pongo docs`.

**Comment by chronolaw** [comment]
> please validate that the documentation still renders properly when changing those helper files.
> 
> ```
> cd spec
> ldoc .
> ```
> 
> should render the docs properly. Users access this through `pongo docs`.

It seems that ldoc did not access `spec/details` directory and lose module information in it, do we have some ideas?

**Comment by Tieske** [comment]
> > please validate that the documentation still renders properly when changing those helper files.
> > ```
> > cd spec
> > ldoc .
> > ```
> > 
> >   
> > should render the docs properly. Users access this through `pongo docs`.
> 
> It seems that ldoc did not access `spec/details` directory and lose module information in it. Shoud we change `config.ld`?

Yup, looks like we need to add those files from their contents

**Comment by chronolaw** [comment]
I think that I have found the solution:
- add module definition header in each separated lua file
- edit `config.ld`, add "./details" in `file`
- add `merge=true`

I will create another PR to fix the doc, do you think it is OK?

**Review by ProBrian — APPROVED** [review]

**Review by Water-Melon — APPROVED** [review]

**Pull request merged**
