### PR TITLE
feat(bazel): build 2.8 CE on Bazel

### PR DESCRIPTION
**Pull request by Water-Melon**
### Summary

Build 2.8 on Bazel.
1. Copy Bazel and build files from EE 2.8.
2. Remove EE-related content.
3. Copy CI-related files from CE master.
4. Make corrections to CI Build.
5. Fix flakiness `spec/03-plugins/34-zipkin/zipkin_spec.lua`.
6. Revert the version of OpenSSL to 1.1.1w.

### Issue reference

KAG-2835

### CODE REVIEW

**Comment by fffonion** [comment]
let's revert the openssl to 1.1.1w on 2.8.x CE

**Review by fffonion — APPROVED** [review]

**Comment by fffonion** [comment]
Reviewers: please also refer to https://github.com/Kong/kong-private/pull/189 for previous review comments

**Review by outsinre — APPROVED** [review]

**Comment by Water-Melon** [comment]
This is the check for all manifests: https://github.com/Kong/kong/actions/runs/7339294338

**Review by ADD-SP — APPROVED** [review]

**Comment by curiositycasualty** [comment]
Posthumous 👍

**Pull request merged**
