### PR TITLE
fix(tests): fix admin-api dbless test typo of matching timers count

### PR DESCRIPTION
**Pull request by fffonion**

### CODE REVIEW

**Comment by fffonion** [comment]
@ADD-SP mentioned this test is no longer needed because of the introduction of timer-ng library, Qiqi could you add more detail here?

**Comment by ADD-SP** [comment]
I think we should not put this test here as a commitly test, because if we want to detect this regression, we need to POST the YAML config many times, so it will take too much time. 

So I think putting this test into the SDET's test set is better than now. 

@Hayk-S What do you think? Feel free to ask for some help from me.

**Review by bungle — DISMISSED** [review]

**Comment by Hayk-S** [comment]
@ADD-SP  Where do you think this test should fit?
Currently, SDETs don't execute any tests in db-less mode.

**Comment by fffonion** [comment]
As future task is tracked, let's move this in for now

**Review by ADD-SP — APPROVED** [review]

**Pull request merged**
