### PR TITLE
fix(admin-api) allow plugin api.lua with schema/method style

### LINKED ISSUE #5291: Kong1.4.1 Admin API /metrics 405 Not Allowed
### Summary

I Updated Kong to 1.4.1 in my computer and tried to get metrics data from http://localhost:5001/metrics by **GET** method, but Kong return **405 Not Allowed**. It works right in 1.4.0.

### Steps To Reproduce

1. Update to Kong 1.4.1
2. Get Request to http://localhost:5001/metrics

### Additional Details & Logs

- Kong version 1.4.1

### PR DESCRIPTION
**Pull request by kikito**
This change fixes a regression introduced in #5174. Said regression consisted on an error which was raised when Kong attempted to parse a plugin `api.lua` file with `schema` and `methods` entries, such as:

```
["<path>"] = {
  schema = <schema>,
  methods = {
    GET = function(self) ... end,
      ...
  }
```

The regression only allowed "lapis-style" entries, such as this one:

```
["<path>"] = {
  GET = function(self) ... end,
  ...
}
```

This made the Prometheus plugin stop working with Kong, which used the first style for its `api.lua`.

This makes Kong accept both styles again.

Fixes #5291

### CODE REVIEW

**Comment by kikito** [comment]
I made sure this PR makes the Prometheus specs pass:
* With the old style https://travis-ci.com/Kong/kong-plugin-prometheus/builds/139513552
* And with the new style https://travis-ci.com/Kong/kong-plugin-prometheus/builds/139556171

**Comment by hutchic** [comment]
I also made sure the prometheus specs fail / pass correctly by cherry-picking https://github.com/Kong/kong/pull/5305 onto your branch

**Comment by hbagdi** [comment]
> I also made sure the prometheus specs fail / pass correctly by cherry-picking #5305 onto your branch

This was with 0.6 version of the prometheus plugin?

**Comment by hishamhm** [comment]
@hbagdi yes. IIRC @hutchic tested with the latest release, and @kikito tested it with multiple versions.

**Pull request merged**
