### PR TITLE
chore(deps) bump lua-multipart version from 0.5.1 to 0.5.4

### LINKED ISSUE #2851: incorrectly parses multipart/form-data
When using the aws-lambda plugin, the body of messages is automatically being parsed when the header is multipart/form-data. The problem is that it doesn't parse it adequately enough, so it's accidentally excluding important parts, or getting some things wrong altogether. There should be someway to forward the raw message.

Here's my example of it wrongly parsing my data:

This is how you parsed my message:
```
{
dkim: '{@weissmaler.de : pass}',
to: 'something+BIG@weissmaler.ch',
subject: 'title',
from: 'Nick Decoursin <nick.decoursin@weissmaler.de>',
SPF: 'softfail',
sender_ip: '10.43.24.23',
email: '--f403045f559c6fcc8b055795cf05\r\n--f403045f559c6fcc88055795cf03\r\nbig\r\n--f403045f559c6fcc88055795cf03\r\n<div dir="ltr">body</div>\r\n--f403045f559c6fcc88055795cf03--\r\n--f403045f559c6fcc8b055795cf05\r\newogICAgIm5hbWUiOiAibXkgbmFtZSIsCiAgICAiYXJlYS1vZi11c2UiOiAi\r\nY2F0IiwKICAgICJ1bml0IjogInNvbWUgdW5pdCIsCiAgICAicGFja2FnZXMi\r\nOiBbCgl7CgkgICAgIm51bS1vZi11bml0cyI6IDQsCgkgICAgInByaWNlIjog\r\nIiQ1LjAwIgoJfSwKCXsKCSAgICAibnVtLW9mLXVuaXRzIjogOCwKCSAgICAi\r\ncHJpY2UiOiAiJDEwLjAwIgoJfV0KfQ==\r\n--f403045f559c6fcc8b055795cf05--' 
}
```

This is the raw message:
```
--xYzZY
Content-Disposition: form-data; name="dkim"

{@weissmaler.de : pass}
--xYzZY
Content-Disposition: form-data; name="subject"

title
--xYzZY
Content-Disposition: form-data; name="email"

Received: by mx0025p1las1.sendgrid.net with SMTP id 136ViLNNJx Fri, 25 Aug 2017 16:19:14 +0000 (UTC)
Received: from mail-wr0-f178.google.com (unknown [10.43.24.23]) by mx0025p1las1.sendgrid.net (Postfix) with ESMTPS id CA2EF22903 for <something+BIG@weissmaler.ch>; Fri, 25 Aug 2017 16:19:13 +0000 (UTC)
Received: by mail-wr0-f178.google.com with SMTP id z91so848344wrc.1 for <something+BIG@weissmaler.ch>; Fri, 25 Aug 2017 09:19:13 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=weissmaler.de; s=google; h=mime-version:from:date:message-id:subject:to; bh=QpbRN2IhVIV7sFjAE/gbHB905/SCCdbIp7heSMkMdJg=; b=t//9/a2ZdyPYwGhExbRB0KBQpFr5mXY1ddtfuZd22Z4wvGoqV7F7Y5DEVxKACDLfLl 4agVtNIO7TWB+AiBL/mrSud95XzF2ghtWb+mKa37GYPiG/MDm/rr2ohUdudkUFlf8jkm IcqczDJs86OdIo62zdkSODmHbdxmCzfiHW2F4+J4S9zfcWx1brR5lbmB7s6gqtrzSDYA GojkqIR+pZX3eD70KE4yn4JXtXlqLmX7NoLUjPA9FI3TEQwEBpCHenN6EWg8gUGDupDG 6A+dR544ko6QWm1jcenTeRNdML3TrkkHahSNGcKsGhYxvtJT7X7R5uQZbfCZK6kB3Hmx 4FLw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=1e100.net; s=20161025; h=x-gm-message-state:mime-version:from:date:message-id:subject:to; bh=QpbRN2IhVIV7sFjAE/gbHB905/SCCdbIp7heSMkMdJg=; b=G0/WOpieZKSjGypaXoWQAPbudI5eYMj5Yppn+IX2dnebPZlBhnSMFp/oOSXeH7+AXM jqm/i/RV+snU9mLuWhHAYGMo9DX0tcLyMOi8sArTp1JDR6DUnfLILJtWgAc9pLNp3y/F GWq9zrQC+Er04CbwLn6hFSkMWY1kP3p8VgfqSaRQBJv8e1J2vlUR01avW4fXIADxQzcP Th4jMxZ6NgWtguKRpXZksC9ML75ppoEewoYRvxfXpvxoCatZa2fOcwzda/k1l/Q7c2wH EOYH2FGsS2+OabaYzZNa4F8rK2XHtbRqPsYqk6212wPdRmio8QS6goOTGQqWLMA/SEoD +CzA==
X-Gm-Message-State: AHYfb5i8WQJKYjHfTTEsXZFYdIHEeOGrafh45cVWs6kphZYUGl/s5RHg PadyJ6unx/cmquiJ1k/WPAW0aJ6jXD3pjGkObQ==
X-Received: by 10.223.154.71 with SMTP id z65mr6068290wrb.218.1503677952191; Fri, 25 Aug 2017 09:19:12 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.223.148.163 with HTTP; Fri, 25 Aug 2017 09:19:11 -0700 (PDT)
From: Nick Decoursin <nick.decoursin@weissmaler.de>
Date: Fri, 25 Aug 2017 18:19:11 +0200
Message-ID: <CAA7sxu7=sT7-4o57AW3chRsf-RFN7p62WcMSz671vsybg+CgZQ@mail.gmail.com>
Subject: title
To: something+BIG@weissmaler.ch
Content-Type: multipart/mixed; boundary="f403045f559c32a3fa0557964ec7"

--f403045f559c32a3fa0557964ec7
Content-Type: multipart/alternative; boundary="f403045f559c32a3f70557964ec5"

--f403045f559c32a3f70557964ec5
Content-Type: text/plain; charset="UTF-8"

body

--f403045f559c32a3f70557964ec5
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">body</div>

--f403045f559c32a3f70557964ec5--

--f403045f559c32a3fa0557964ec7
Content-Type: application/json; name="working.bak.json"
Content-Disposition: attachment; filename="working.bak.json"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_j6s30z2j0

ewogICAgIm5hbWUiOiAibXkgbmFtZSIsCiAgICAiYXJlYS1vZi11c2UiOiAi
Y2F0IiwKICAgICJ1bml0IjogInNvbWUgdW5pdCIsCiAgICAicGFja2FnZXMi
OiBbCgl7CgkgICAgIm51bS1vZi11bml0cyI6IDQsCgkgICAgInByaWNlIjog
IiQ1LjAwIgoJfSwKCXsKCSAgICAibnVtLW9mLXVuaXRzIjogOCwKCSAgICAi
cHJpY2UiOiAiJDEwLjAwIgoJfV0KfQ==

--f403045f559c32a3fa0557964ec7--

--xYzZY
Content-Disposition: form-data; name="to"

something+BIG@weissmaler.ch
--xYzZY
Content-Disposition: form-data; name="from"

Nick Decoursin <nick.decoursin@weissmaler.de>
--xYzZY
Content-Disposition: form-data; name="sender_ip"

10.43.24.23
--xYzZY
Content-Disposition: form-data; name="envelope"

{"to":["something+BIG@weissmaler.ch"],"from":"nick.decoursin@weissmaler.de"}
--xYzZY
Content-Disposition: form-data; name="charsets"

{"to":"UTF-8","subject":"UTF-8","from":"UTF-8"}
--xYzZY
Content-Disposition: form-data; name="SPF"

softfail
--xYzZY--
```
Your parsed event is completely missing the `Content-Disposition: attachment` part, and it's incorrectly parsing the `Content-Disposition: form-data; name="email"` part.

As such, the aws-lambda plugin is useless to me how it stands now, since I'm unable to modify the request since it's a direct message from sendgrid.

### LINKED ISSUE #2981: request-transformer only last body parameter added when multipart/form-data
### Summary

request-transformer plugin adds only last form parameter (another-form-param) with _config --data "config.add.body=new-form-param:some_value, another-form-param:some_value"_ **when content type is multipart/form-data** Parameter new-form-param or another-form-param is not defined on request.

### Steps To Reproduce

1. Use request-transformer with config:  --data "config.add.body=api_key:jf34rn23lrn2krn2de213ef,jurisdiction_id:test"
2. Send multipart/form-data request. Only jurisdiction_id is added.
3. Swap parameters. Change  request-transformer config to:  --data "config.add.body=jurisdiction_id:test,api_key:jf34rn23lrn2krn2de213ef"
4. Send multipart/form-data request. Only api_key is added.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.11.0
- Operating System Ubuntu 16.04.3 LTS

### LINKED ISSUE #3024: request-transformer plugin fails if multipart/form-data contains file
### Summary

When request-transformer plugin enabled, multipart/form-data coded file sending through Kong fails. Everything seems to be fine until Request Transformer plugin is added. When sending file and Request Transformer plugin is activated, result is [{"code":400,"description":"An internal error occurred"}]

### Steps To Reproduce

1. Send multipart/form-data coded file through Kong. That is ok.
2. Enable request-transformer plugin.
3. Send multipart/form-data coded file through Kong. Sending fails with message [{"code":400,"description":"An internal error occurred"}]

### Additional Details & Logs

- Kong version (`$ kong version`) 0.11.1
- Operating System Ubuntu 16.04.3 LTS

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Bump lua-multipart version from 0.5.1 to 0.5.4.

### Issues resolved

Fix #3024 
Fix #2981
Fix #2851
Fix https://github.com/Kong/lua-multipart/issues/12

### CODE REVIEW

**Comment by thibaultcha** [comment]
@bungle Let us know if 0.5.2 still a desired bump or should we delay this as per the recent developments on the linked issues (that seem to still indicate the presence of bugs)? If not, I suggest closing this and reopening it at a later time!

**Comment by bungle** [comment]
This needs update when this is merged: 
https://github.com/Kong/lua-multipart/pull/15

**Comment by bungle** [comment]
@thibaultcha Yes, it is desired. The main thing is whether this goes to `0.12`or `0.13`.

**Comment by bungle** [comment]
This needs one additional fix. Not that the previous ones didn't do fixes, but that there were even more issues. I hope soon to be released `0.5.4` will finally make this library to not corrupting uploads with e.g. request-transformer.

**Comment by thibaultcha** [comment]
@bungle Probably best to rebase this on top of master! :) Feel free to merge then

**Pull request merged**
