### PR TITLE
chore(*) import aws lambda

### PR DESCRIPTION
**Pull request by gszr**
As a result of an effort to improve external plugins maintainership, we are importing currently-bundled plugins into Kong's main tree. The aws-lambda plugin used to live in [1].

Additionally to importing plugin contents, this PR also preserves the Git history. History was amended to correct commit scopes - including `aws-lambda` in commit messages scope.

~Note: test failure observed here is the same as observed in current `master`.~ (already fixed)

[1] https://github.com/Kong/kong-plugin-aws-lambda/

### CODE REVIEW

**Review by bungle — APPROVED** [review]

**Review by Tieske — COMMENTED** [review]
Can we please not merge this pending internal discussion?

**Comment by gszr** [comment]
@jonminter @MosAmokhtari @chasingmaxwell  @ezrapagel @verisk-dhaskin My apologies to bug you all, but would you mind re-signing the CLA, so we can incorporate this plugin into Kong's tree? It was already signed in the aws-lambda repository, but as it's a separate repo, it doesn't show up here.

**Comment by PaulFischer-Kong** [comment]
> Can we please not merge this pending internal discussion?
@Tieske just as a heads up, the planned merge is continuing. I'm available for you on ensuring Field/CX is best equipped to handle the change.

**Comment by Tieske** [comment]
@PaulFischer-Kong If we're going ahead with this, can we then at least NOT install them as part of Kong, but keep the separate rockspecs and use those to install/uninstall the plugins. Still gives all the benefits of mono-repo, but also allows independent usage.

**Comment by gszr** [comment]
Hey @MosAmokhtari, @jonminter, @verisk-dhaskin, sorry to bug again - could you sign the CLA so we can proceed with this PR?

**Comment by jonminter** [comment]
@gszr Apologies for the long delay sorry for holding this up, CLA has been signed.

**Comment by gszr** [comment]
> @gszr Apologies for the long delay sorry for holding this up, CLA has been signed.

Not a problem, @jonminter! Thank you for signing it.

**Pull request merged**
