### PR TITLE
feat(wasm): add support for wasmtime cache

### PR DESCRIPTION
**Pull request by flrgh**
Loading .wasm module binaries involves a compilation step before they can be executed, which can slow Kong's startup time. This enable's Wasmtime's builtin cache, such that subsequent start/stop/restart cycles can be faster with a warm cache.

See also:

* [Wasmtime doc](https://docs.wasmtime.dev/cli-cache.html)
* [ngx_wasm_module cache_config doc](https://github.com/Kong/ngx_wasm_module/blob/main/docs/DIRECTIVES.md?plain=1#L136-L149)
* [ngx_wasm_module PR](https://github.com/Kong/ngx_wasm_module/pull/540)

KAG-4372

### CODE REVIEW

**Comment by brentos** [comment]
Is it possible to add a test for restarting kong with the cache enabled? Otherwise LGTM

**Comment by flrgh** [comment]
@brentos

765baba47d1f92d83094315a0e349880fdf08eed adds an integration test for start/restart. There's not a lot we can inspect and assert upon without making sketchy assumptions about wasmtime's cache implementation, so this test just checks for anything in `error.log` that looks like a problem.

**Comment by brentos** [comment]
> @brentos
> 
> [765baba](https://github.com/Kong/kong/commit/765baba47d1f92d83094315a0e349880fdf08eed) adds an integration test for start/restart. There's not a lot we can inspect and assert upon without making sketchy assumptions about wasmtime's cache implementation, so this test just checks for anything in `error.log` that looks like a problem.

Yeah mainly i wanted to make sure nothing broke by introducing the cache, that things work with existing cache files on restart. Thanks!

**Comment by flrgh** [comment]
@locao / @kikito I could use help getting a second reviewer for this

**Review by locao — APPROVED** [review]
LGTM

**Comment by flrgh** [comment]
> Cherry-pick failed for `master`, because it was unable to cherry-pick the commit(s).
> 
> Please cherry-pick the changes locally.
> 
> ```shell
> git remote add upstream https://github.com/kong/kong-ee
> git fetch upstream master
> git worktree add -d .worktree/cherry-pick-12930-to-master-to-upstream upstream/master
> cd .worktree/cherry-pick-12930-to-master-to-upstream
> git checkout -b cherry-pick-12930-to-master-to-upstream
> ancref=$(git merge-base 4052fbbfee77be52bcd5c876719a84bcbc8ba337 296ccb531a142cc5dafc428e24af60646de84372)
> git cherry-pick -x $ancref..296ccb531a142cc5dafc428e24af60646de84372
> ```

Manually cherry-picked: https://github.com/Kong/kong-ee/pull/9389

**Pull request merged**
