### PR TITLE
feat(plugin)(correlationId) increase priority order for plugin to mat…

### PR DESCRIPTION
**Pull request by andrewgkew**
### Summary

Increase priority order for plugin to match EE so it can be used in other/custom plugins

### Checklist

- [x] The Pull Request has tests (updated tests already there due to this change)
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - https://github.com/Kong/docs.konghq.com/pull/7801

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Comment by jeremyjpj0916** [comment]
I patch my existing correlation id plugin in our own runtimes to execute earliest too as it makes sense to be able to capture that in other http logging plugins etc.

**Review by gszr — APPROVED** [review]

**Review by dndx — APPROVED** [review]

**Comment by bungle** [comment]
Can we do this in `non-major` release, as it is a breaking change?

**Comment by gszr** [comment]
> Can we do this in `non-major` release, as it is a breaking change (though having this difference does make moving from CE to EE an vice-versa as a potentially breaking too)? Personally I am fine with that.

Generally, changing plugins ordering is a breaking change and should be avoided in a non-major; especially if the change decreases the priority - ie, its side effects cease being visible to plugins it previously was visible. In this particular case, this does not happen: it expands the list of plugins that have access to the id. Also, there's no change in functionality. I would say it's okay to merge in a minor or even a patch.

**Review by gszr — APPROVED** [review]

**Comment by andrewgkew** [comment]
@gszr - when do you think this will make it in a version of CE?

**Comment by gszr** [comment]
> @gszr - when do you think this will make it in a version of CE?

This will likely be included in 3.9, which is planned for late December.

**Comment by gszr** [comment]
@andrewgkew could you add a changelog entry under `changelog/unreleased/kong`? I will be happy to merge it thereafter.

**Comment by kikito** [comment]
Since this change already exists in kong ee, cherrypicking is not necessary. Removing the cherrypick labels.

**Pull request merged**
