### PR TITLE
Fixed issue where redis key expiration time was overwritten in concur…

### PR DESCRIPTION
**Pull request by GQH1993**
…rent cases

### Summary

SUMMARY_GOES_HERE

### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issues resolved

Fix #XXX

### CODE REVIEW

**Comment by hbagdi** [comment]
@GQH1993 Question for my understanding: can you explain when does this problem actually occur?

**Comment by GQH1993** [comment]
> @GQH1993 Question for my understanding: can you explain when does this problem actually occur?
Concurrent request flow limiting plug-in,the expiration time for the newly created key is overwritten multiple times

**Comment by GQH1993** [comment]
> @ GQH1993我所理解的问题：您能解释一下这个问题何时真正发生吗？

@hbagdi Concurrent request flow limiting plug-in,the expiration time for the newly created key is overwritten multiple times.

**Comment by bungle** [comment]
As this was merged:
https://github.com/Kong/kong/pull/6150

I think this PR is now redundant. @GQH1993, please reopen and rebase if that was not the case.

**Pull request closed without merging**
