### PR TITLE
fix(opentelemetry): http.uri should be full path

### LINKED ISSUE #10036: kong produce spans which are not compatible to opentelemetry specification in http.url
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

?

### Current Behavior

Kong with tracing enabled, sending spans over otlp.
The produced spans has an attribute `http.url` set [here](https://github.com/Kong/kong/blob/d6dd5dd4844eec4f973424739a6b686d1e452993/kong/tracing/instrumentation.lua#L200) which contains `ctx.request_uri` [which is the **HTTP target**](https://www.webhosting24.com/understanding-nginx-request_uri/) if I understand it correctly. According to [the opentelemetry semantic conventions for HTTP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md):

Attribute | Type | Description | Examples | Requirement Level
-- | -- | -- | -- | --
http.url | string | Full HTTP request URL in the form scheme://host[:port]/path?query[#fragment]. Usually the fragment is not transmitted over HTTP, but if it is known, it should be included nevertheless. [1] | https://www.foo.bar/search?q=OpenTelemetry#SemConv | Required

The `http.url` attribute should contain the **Full HTTP url**, e.g. `https://www.foo.bar/search?q=OpenTelemetry#SemConv` and not `/search?q=OpenTelemetry#SemConv` as is currently implemented. This causes the spans from kong to not be processable by backends that try to parse this attribute as full URL according to the spec

### Expected Behavior

Expected the value in `http.url` attribute to contain the full URL according to the specification, or for the value to be recorded into `http.target` which is the correct attribute for this value

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by StarlightIbuki**
fix #10035 KAG-377

### CODE REVIEW

**Comment by StarlightIbuki** [comment]
@mayocream Seems like we do not even have a test for this field?

**Comment by mayocream** [comment]
> @mayocream Seems like we do not even have a test for this field?

Let's add one instead

**Review by colinh-kong — APPROVED** [review]
approved pending a test

**Comment by dndx** [comment]
@StarlightIbuki This needs rebasing. Also is there a Jira ticket number for this fix?

**Comment by StarlightIbuki** [comment]
> @StarlightIbuki This needs rebasing. Also is there a Jira ticket number for this fix?

Conflict solved.

**Review by dndx — APPROVED** [review]

**Pull request merged**
