### PR TITLE
perf(balancer) optimize for less table resize

### PR DESCRIPTION
**Pull request by bungle**
Trying to get rid of tab_resize and perhaps the new_key too:
image

### CODE REVIEW

**Comment by fffonion** [comment]
[flamegraphs.zip](https://github.com/Kong/kong/files/7171034/flamegraphs.zip)

**Review by fffonion — APPROVED** [review]
I can verify handler:before appears to take less portion of time in flamegraph.

**Review by javierguerragiraldez — APPROVED** [review]
this is a good pattern. struct-like tables are at their best when all keys are defined in the table constructor

**Comment by bungle** [comment]
Relevant piece of flamegraph:
image

**Pull request merged**
