### PR TITLE
feat(tools) add `verbatim` parameter to `responses.send`

### PR DESCRIPTION
**Pull request by salazar**
### Summary
`send_response` unconditionally encodes responses as JSON. This PR adds support for verbatim responses, extending the `send` function with a 4th argument `verbatim`, which, if true, results in the `body` argument being interpreted as a string and returned verbatim in the response body.

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Just wondering, might it allow for more flexibility if the response generator could accept many content types, similar to `kong.core.error_handlers`?

**Comment by salazar** [comment]
@p0pr0ck5 the closure returned by `send_response` takes in a headers table, over which we can pass the content type header.

**Comment by p0pr0ck5** [comment]
Yes but the body formatting is handled differently in each case, no (as evidenced by this PR)?

**Comment by salazar** [comment]
@p0pr0ck5 what this PR seeks is allowing the caller to return a certain response as is - without it being modified in any way (like core error handlers do, by applying a certain template depending on the response type); so it's that exact body formatting that it avoids

**Comment by p0pr0ck5** [comment]
Yep, I understand that :)

My question was, for consistency sake (as well as for future flexibility), should Kong-synthesized responses support a variety of content types? For example, I have a custom plugin that writes out data in XML- it would be great if I could use this module to do that, rather than writing my own content writer and duplicating a bunch of code. Again, just thinking out loud here.

**Comment by salazar** [comment]
@p0pr0ck5 that would be a nice contribution - providing Kong-synthesized, templated, responses _and_ a verbatim mode - e.g., to be used in plugins that want absolute control over the response ! :)

**Comment by thibaultcha** [comment]
We are working on the plugins SDK these days which will have response-producing capabilities. Fir this particular PR, better to use `ctx.delayed_response_callback` as it was implemented for this precise use-case, and this PR is a re-implementation of it (but without delayed responses which is a step backwards).

**Pull request closed without merging**
