### PR TITLE
WIP: feat(jwt) revoke all consumer jwt credentials

### PR DESCRIPTION
**Pull request by aloisbarreras**
### Summary

This is a WIP for the discussion with @thibaultcha on Kong Nation [here](https://discuss.konghq.com/t/admin-api-route-to-delete-all-credentials-for-consumer/1393).

Looking for some initial feedback to make sure I'm going in the right direction of how you guys would implement this. I'm also fairly new to the Kong universe and will definitely need some help getting this functionality across the finish line :).

### Full changelog

* adding new delete_where function to the postgres dao
* adding admin API route to delete jwt credentials for a consumer

### CODE REVIEW

**Comment by thibaultcha** [comment]
Hi there,

Back from vacation, I haven't had time to take a look at this yet, sorry. We haven't forgotten though, hopefully we'll come to it next week or so. Thanks!

**Comment by safinilnur** [comment]
Nice PR. While deleting/blocking user, it will be cool to revoke all tokens with 1 request

**Comment by hishamhm** [comment]
@safinilnur at this point this PR is based on the Kong 0.x codebase, so it would take some reworking to get it to use the Kong 1.x modules... not sure if @aloisbarreras would be interested in bringing it up to date. There are also open questions about deletion vs. revocation in general (would people using the `revoke` endpoint expect it to maintain an internal revocation list instead of just deleting the data?)

**Comment by hishamhm** [comment]
@aloisbarreras Are you planning to get back to this PR, or should we perhaps close this for now and get back to it some other time? Thank you!

**Comment by hishamhm** [comment]
Closing this one — feel free to reopen if you wish to get back to it! Thanks!!

**Pull request closed without merging**
