### PR TITLE
Backport 9485

### PR DESCRIPTION
**Pull request by poelzi**
### Summary

This is a backport of #9485 to the 2.8 release branch

### Issue reference

#9485
#9090

### CODE REVIEW

**Comment by poelzi** [comment]
can i get a approval ?

**Comment by chronolaw** [comment]
Thanks for your concern.

We have our own version plan, we only choose the necessary PR for the old release branch.
I think that we need an evaluation for this.

**Comment by poelzi** [comment]
Our customers upgrade path is blocked by this. Also some comments in the reports indicate that we are not the only one having issues with this.

**Comment by outsinre** [comment]
We encourage our customers to use 3.0 onwards. We don't backport 3.0 commits to 2.8.x unless manager approval. Otherwise, all customers want things in 3.0 backported to 2.8.x, which is undesirable. We'd like our engineer bandwidth focus on the main major version.

**Pull request closed without merging**
