### PR TITLE
renaming internal `balancer_data` structure

### PR DESCRIPTION
**Pull request by Tieske**
The initial attempt to refactor the request construction (see #3744) is now phased into multiple PR's

First one being the refactor of the request path building (#3780 ), this is the second one where the internal structures are renamed and expanded. The routing properties will now be set AFTER the access phase.

### CODE REVIEW

**Comment by thibaultcha** [comment]
@Tieske Please avoid opening WIP PRs, as it adds some overhead on our side. Working on a fork would allow you to still benefit from the Travis CI jobs (on your own account) while the PR is being worked on.

**Comment by p0pr0ck5** [comment]
Do we still need this open?

**Comment by thibaultcha** [comment]
Yes, this is still relevant but was postponed to post 1.0

**Comment by Tieske** [comment]
replaced by #4653

**Pull request closed without merging**
