### PR TITLE
feat(cluster) enable access log on cluster listener

### LINKED ISSUE #6589: No logs for dp -> cp communications
The CP listener has no access logs configur-ed/able? see https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong.lua#L440-L447

I was troubleshoting DP/CP connections and expected logs to help out, but there are none…

They would be helpful for setting things up. So we should probably write them to the same log files imo, so we don't have to use yet another set of config options. And volume is really low, so that shouldn't be an issue.

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Enables access logs on cluster listener and writes logs to admin access log.

### Issues Resolved

Fix #6589

### CODE REVIEW

**Review by Tieske — COMMENTED** [review]
lgtm

**Comment by Tieske** [comment]
minor note: probably in the config file we should make a comment at the cluster_listen listener that the logs will be in admin access/error log files, to make sure we document this

**Review by dndx — APPROVED** [review]

**Comment by dndx** [comment]
@Tieske this was added in https://github.com/Kong/kong/pull/6599/commits/58e453cdb7ab264a24cf073b63691a1022473dea.

**Comment by Tieske** [comment]
Thnx great doc comments ❤️

**Pull request merged**
