### PR TITLE
feat(runloop) upstream redirects

### PR DESCRIPTION
**Pull request by kikito**
### Summary

Alters the Location response header returned by Upstreams in a very specific case, when the host:port coincides with the matched one by the router.

### Full changelog

In addition to the `feat` change itself, this PR includes a couple changes in the tests.

### Issues resolved

Fixes (partially) #839

### CODE REVIEW

**Comment by kikito** [comment]
The reason why this is sent as a "Draf" is because I want to invite some discussion.

Questions:

* Right now this cover a very specific circumstance. Should we include others? For example, if the matched occurrs via a `/foo` path in the Route, and the returned `Location` is `http
://<upstream_host:upstream_port>/foo`, where upstream_host and upstream_port coincide with the service host, should we remove the upstream host and port and lust leave `/foo`?
* Should this behavior be part of Kong itself, and be active all the time? It could definitively be exported to a plugin, and be applied only to certain routes.

**Comment by guanlan** [comment]
Should we feature flag this new redirect behavior?

**Comment by Tieske** [comment]
Imo it should be a plugin. Wrt implementation then this seems only a rather narrow use case. If this is added, we should be prepared for requests to enhance it to support all transformations done, including the stripping and prefixing of the path.

**Comment by bungle** [comment]
I am leaning towards plugin too. The current implementation is always on, and that is not what people always want, especially as Kong has never done that before. If not a plugin, it should be a property of  `service` I think.

**Comment by kikito** [comment]
Ok it seems that "move this to a plugin" is decided. I think I like that approach because it allows further tweaking (a plugin can have several options instead of just a `enabled/disabled` boolean). This also made me think about a different approach. The problem which we are trying to solve on this PR is this:

> if the upstream responds with a redirect, typically it will send an absolute path that will not match the one Kong clients are calling (both request host and request path).

I am thinking that the ... "intelligent" approach shown on this pr (where the transformations to the headers are "deduced from the current setup in an implicit way" are difficult to explain, and even after explaining them, they are difficult to know how they will work, exactly.

I believe this is because they are very "indirect". Perhaps a more direct approach would be more straightforward.

What I am thinking about is a plugin which is "`response-transformer` for headers".

Example scenario:

We have a Service/Upstream matching named `myhost.dev`.
It has two targets, with IP addresses `10.20.30.40` and `10.20.30.41`.

What we want is to perform some transformations on the response headers if:
* A responses with a `Location` header AND
* The response http status was a redirect (301, 302, 307, 308)

For requests meeting those requirements, we want:
* If `Location` is from a host like `10.20.30.40` or `10.20.30.41`, we want to replace it with `myhost.dev`
* If `Location` is a relative path (starts with `/`) we want to prefix that with `http://myhost.dev`)

Our fictional plugin could be written like this, and be associated with the Service:

```
{ name = "response-header-transformer",
  config = {
    { rules = {
        { -- array, can have more than 1 rule
          http_status = { 301, 302, 307, 308 },
          header = "location",
          replace = {
            { host = "10\.20\.30\.40", with = "myhost.dev" },
            { host = "10\.20\.30\.41", with = "myhost.dev" }
            { host = "", with = "myhost.dev" }
          }
        }
     }
  }
}
```

The exact config syntax is made up & provisional, but I hope this gets the idea across: the plugin would do some `if`s on the `header_filter` phase and if the conditions are met then it will parse the Location headers and perform a bunch of transformations to it using `ngx.re.sub` before sending it back downstream.

A similar setup could be done for Routes and the `/path` setting, with `replace = { path = ... }` rules.

Advantages: it is easy to know what the plugin does, there is no "built-in magic". The user is the one who decides which particular transformations occur.

Disadvantages:

* If the user adds another target to the upstream they must remember to add another entry to the rules transform. (On this particular case they can probably set a regex which matches a range, but that won't always be an option).
* Using regexes to manipulate domains is iffy, but less so than manipulating whole uris. If you want more fine tuning you are almost to the point where you want to write your own plugin I think.

**Comment by locao** [comment]
Closing this as we decided to move the feature to plugins.

**Pull request closed without merging**
