### PR TITLE
perf(core) remove coroutine in access plugins iterator

### PR DESCRIPTION
**Pull request by mayocream**
### Summary

Remove `coroutine` in access plugins iterator

WIP

### CODE REVIEW

**Comment by Tieske** [comment]
This would be great. That coroutine has given me so many “attempt to yield across c call boundary” errors.

**Comment by bungle** [comment]
> This would be great. That coroutine has given me so many “attempt to yield across c call boundary” errors.

Do you have an example? There is a big reason for that to exits, and it is to collect plugins even when one plugin said `kong.response.exit` or even `ngx.exit`.

**Comment by Tieske** [comment]
@bungle Interactive debuggers, and don’t recall whether maybe luacov also had an issue with it

**Comment by hbagdi** [comment]
Closing because of lack of activity. 2.7 is not receiving updates anymore.

**Pull request closed without merging**
