### PR TITLE
added LDAPS support in auth-ldap plugin

### PR DESCRIPTION
**Pull request by gauauu**
### Summary

This PR adds an option for LDAPS support (ie LDAP over SSL) to the ldap connection.  This addresses the request for LDAPS in issue (https://github.com/Mashape/kong/issues/1393)

### Full changelog

* Added boolean configuration schema option for LDAPS in ldap-auth plugin
* Added connection code to handle the new configuration option
* ...

### Issues resolved

Addresses the feature requests buried in #1393

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
@gauauu I'm a bit confused, by setting `start_tls` in the plugin config, we already call `sslhandshake` on the socket? @shashiranjan84 can you provide some context here?

**Comment by gauauu** [comment]
This would be used instead of StartTLS.  Some ldap servers are configured to use LDAPS on port 636 but don't support STARTTLS.   Currently using this module on those servers results in the issue found in #1393.  With my change, you can leave STARTTLS disabled, but still use LDAPS, and it will work for those cases.

**Comment by gauauu** [comment]
That said, I realize there might be a better option for configuration instead of two binary flags, and would be happy to change how that works if necessary.

**Comment by shashiranjan84** [comment]
@p0pr0ck5 `STARTTLS` encrypts the existing connection and that what usually advised to use for securing the data. But @gauauu  is right ,  some ldap servers are only configured to use LDAPS on port 636. We can use this PR with some changes.

@gauauu How about  adding a check in schema that validates that only one `STARTTLS` or `LDAPS` is enabled and some test for that?

I will take care integration test as it would need to enable `LDAPS` on test server.

**Comment by gauauu** [comment]
@shashiranjan84  That suggestion makes sense, I'll see what I can do.  I'll need to learn a little more about how Kong handles schema options, but I'll take a look.

**Comment by shashiranjan84** [comment]
@gauauu please check this guide https://getkong.org/docs/0.10.x/plugin-development/plugin-configuration/

You can also use following implementation as help 
https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/schema.lua

Thanks again for PR.

**Comment by gauauu** [comment]
Perfect, thanks.  Having an example will be really helpful.

**Comment by gauauu** [comment]
Ok, I've added the self_check and a spec test.   Let me know if you have additional feedback.  There's probably some other tests that should be created in the ldap spec to fully test the requirements for it, but it seemed like this PR wasn't the right place to add them.

**Comment by Tieske** [comment]
@shashiranjan84 can you have a look at this one please?

@gauauu A docs PR to describe the changes (see https://github.com/Mashape/getkong.org) would be most welcome

**Comment by thibaultcha** [comment]
@shashiranjan84 Mind giving this another look?

Also, any suggestion (@gauauu or @shashiranjan84) as to how we could test this feature?

**Comment by shashiranjan84** [comment]
@thibaultcha I ll make it part of next sprint.

**Comment by gauauu** [comment]
I've added a documentation PR at https://github.com/Kong/getkong.org/pull/544

For testing, I don't have enough knowledge of your test framework to give advice about the best way to test (other than setting up an ldaps server just to test the connection, ugh)

**Comment by Gatusko** [comment]
What about the support LDAPS for LDAP plugin Kong?

**Comment by evanchaoli** [comment]
@gauauu This PR has been  a while, can you please continue to work on it. My company's LDAP server only support LDAPS, so that I cannot use Kong to do LDAP authentication.

I tried to port the key piece of code to my local Kong installation, and approved it works. So please fix the conflict and get this PR merge. Thanks a lot.

**Comment by gauauu** [comment]
@evanchaoli I'm glad you got it to work.  

If I get some spare time I might look at the merge conflict, but I'm not really planning to maintain this PR for years. If they don't want to merge it, that's ok, but I don't have time to keep it up-to-date with every change they make -- I've moved on to other projects by now.  Sorry :-)

**Comment by kikito** [comment]
Closing this PR as it was redone in #4743 .

Apologies for the time it took us to get this one in.

**Pull request closed without merging**
