### PR TITLE
perf(vars) use index to access variables

### PR DESCRIPTION
**Pull request by fffonion**
Related: https://github.com/Kong/lua-kong-nginx-module/pull/19

### CODE REVIEW

**Comment by fffonion** [comment]
not running the performance tests here since it doesn't take custom built binary in tests

**Comment by bungle** [comment]
> not running the performance tests here since it doesn't take custom built binary in tests

Yes, I have seen this too, perhaps it is because the branch has `-` and `/`, I am not sure, but I believe this used to work. Last time I tried, I had same problem.

**Review by dndx — APPROVED** [review]

**Comment by utix** [comment]
I think there is an issue with this Pull Request.
Pongo cannot launch test because resty.kong.var is missing.
@fffonion can you check ?

Example of output:
```
 Error: /kong-plugin/kong/cmd/start.lua:64: nginx: [error] init_by_lua error: /kong-plugin/kong/init.lua:543: module 'resty.kong.var' not found:No LuaRocks module found for resty.kong.var
	no field package.preload['resty.kong.var']
	no file './spec/fixtures/custom_plugins/resty/kong/var.lua'
	no file '/kong-plugin/resty/kong/var.lua'
	no file '/kong-plugin/resty/kong/var/init.lua'
	no file '/usr/local/openresty/site/lualib/resty/kong/var.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/kong/var/init
```

**Comment by utix** [comment]
Another issue is tests from `spec/03-plugins/31-proxy-cache/04-invalidations_spec.lua` are not working anymore



```
Error → ...spec/03-plugins/31-proxy-cache/04-invalidations_spec.lua @ 20
proxy-cache invalidations via: cassandra setup
...spec/03-plugins/31-proxy-cache/04-invalidations_spec.lua:73: Error: nginx configuration is invalid (exit code 1):
nginx: [emerg] unknown directive "lua_kong_load_var_index" in /kong/servroot2/nginx-kong.conf:50
nginx: configuration file /kong/servroot2/nginx.conf test failed
```

**Comment by fffonion** [comment]
@utix This PR is targeted for 2.6, meaning you will need the 2.6 image or build from source. The binary must match
the source code you are using.

**Pull request merged**
