### PR TITLE
perf(db): use lmdb transaction with :page/:each

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Uses `lmdb` transaction instead of individual `lmdb.get` calls when  reading pages of data.

@ADD-SP can we do some benchmarking of this?

### CODE REVIEW

**Comment by dndx** [comment]
@bungle Are we still working on this? I think the coredump has been fixed and we should try again.

**Comment by kikito** [comment]
Leaving this for perf evaluation until after releasing 3.5.0

**Comment by bungle** [comment]
This is also related: https://github.com/Kong/kong/pull/11184

**Comment by kikito** [comment]
Superseded by the prefix lookup on lmdb change

**Pull request closed without merging**
