### PR TITLE
feat(tracing): support aws xray propagation

### PR DESCRIPTION
**Pull request by antoine-labarussias-wmx**
This PR adds support for the AWS X-Ray trace propagation header.

### Summary

Because Amazon X-Ray uses a custom trace id format, without proper support of the `X-Amzn-Trace-Id` header, it's not possible to store kong's traces in xray.

Doc about `X-Amzn-Trace-Id`:
https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader

Existing implementations in JS and Python:
 - https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/propagators/opentelemetry-propagator-aws-xray/src/AWSXRayPropagator.ts
 - https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/propagator/opentelemetry-propagator-aws-xray/src/opentelemetry/propagators/aws/aws_xray_propagator.py

### Checklist

- [x] The Pull Request has tests
- [x] There's an entry in the CHANGELOG
- [x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - https://github.com/Kong/docs.konghq.com/pull/5732

### Full changelog

* Implement support for the AWS X-Ray trace header

### CODE REVIEW

**Review by hanshuebner — COMMENTED** [review]
This change looks good overall, thank you for the contribution! Please see my inline comments and add an entry to `CHANGELOG.md`.  If you could suggest what needs to be added to the [documentation](https://docs.konghq.com/hub/kong-inc/opentelemetry/) ([source](https://github.com/Kong/docs.konghq.com/blob/main/app/_hub/kong-inc/opentelemetry/_index.md)), it'd be much appreciated.

**Review by samugi — COMMENTED** [review]
looks good overall! I just left a couple of minor comments

**Review by hanshuebner — APPROVED** [review]

**Comment by outsinre** [comment]
cherry-pick to EE?

**Review by GGabriele — COMMENTED** [review]
Edit: sorry, wrong repo 🤦

**Pull request merged**
