### PR TITLE
chore(ci): customize backport PR title

### PR DESCRIPTION
**Pull request by vm-001**
Replace "Backport" with 🍒 to make the PR title little bit shorter

### CODE REVIEW

**Comment by vm-001** [comment]
Or leaves your favorite emoji to replace "Backport"

**Comment by dndx** [comment]
@vm-001 Could you provide an example (like a screenshot) of what the PR title will look like after the merge?

**Comment by vm-001** [comment]
Here is a example: https://github.com/vm-001/kong/pull/7

**Comment by hbagdi** [comment]
I recommend suffixing with "backport" - it makes searching for all backport PRs possible, I'm not sure if Github can search based on emojis.

**Pull request closed without merging**
