### PR TITLE
chore(plugins) remove deprecated BasePlugin

### PR DESCRIPTION
**Pull request by javierguerragiraldez**
It has been removed from the docs for some time, but the core still
has to check each method to see if it's actually reimplemented or just
inherited.

Updated several fixture plugins that still used it.

### CODE REVIEW

**Comment by Tieske** [comment]
Finally 🎆 

There's no milestone attached. Since this is breaking, this would go in 3.0 I presume?

**Comment by javierguerragiraldez** [comment]
> Since this is breaking, this would go in 3.0 I presume?

I guess it depends on how long has it been deprecated.  It was removed from docs since 2.4.x

**Comment by javierguerragiraldez** [comment]
@aboudreault is the only change in the `.requirements` file?   great

**Comment by aboudreault** [comment]
@javierguerragiraldez I just rebased on latest master and fixed the conflicts in the changelog and the plugin_iterator.lua files.

**Pull request merged**
