### PR TITLE
Manually selectively backport #13052

### PR DESCRIPTION
**Pull request by AndyZhang0707**
### Summary

Manually backport some commits from #13052

Besides the commits cherry-picked from #13052, we've also added a few changes to work with openssl 1.1.1.

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference
KAG-4790

Fix #_[issue number]_

### CODE REVIEW

**Comment by AndyZhang0707** [comment]
release dry run: https://github.com/Kong/kong/actions/runs/10067808142

**Comment by AndyZhang0707** [comment]
Release dry run: https://github.com/Kong/kong/actions/runs/10069711232

**Review by Water-Melon — APPROVED** [review]

**Comment by chronolaw** [comment]
Please give this PR a proper title, like `chore(ci): ...`

**Comment by AndyZhang0707** [comment]
> Please give this PR a proper title, like `chore(ci): ...`

Hi @chronolaw , this PR needs to be "rebase and merge" thus the subject doesn't follow our convention (I didn't want to follow the convention to avoid someone click the "squash and merge"). Please help review the individual commit messages. Thanks

**Pull request merged**
