### PR TITLE
style(cli) remove Lua comment markers

### PR DESCRIPTION
**Pull request by Tieske**
The markers should be removed since it is now a long string, and not source code.

### CODE REVIEW

**Comment by bungle** [comment]
@Tieske how about this:
```

```                                                                            ````````                                                                       ````````````                                                                  ``````````````````                                                             ``````````````````````                                                          ``````````````````````````                                                      `````````````````````````````                                                             ```````````````````                                                    ```````    ``````````````````                                                  ```````````    ``````````````````                                               ``````````````    ````````````````                                              `````````````````   ```````````````                                             ```````````````````    ```````````                                              ``````````````````````    ```````                                               `````````````````````````   ```                                                   `````````````````````````                                                   ```    `````````````````````````                                              ````````    `````````````````````````                                          ````````````    ````````````````````````                                       ```````````````    `````````````````````````                                  ````````````````````    `````````````````````````                          ````````````````````````````    ````````````````````````                        ``````````````````````````````    `````````````````````````                    ``````````````````````````````````    `````````````````````````                 `````````````````````````````````````    `````````````````````````             ``````````````````````````````````````      `````````````````````````           ``````````````````````````````````````         `````````````````````````       ```````````````````````````````````````            `````````````````````````    ````````````````````````                             `````````````````````````   ```````````````````````                                ````````````````````````` `````````````````````    `````````````````               ``````````````````````` ````````````````````     ```````````````````              `````````````````````  ``````````````````        ````````````````````              ```````````````````  `````````````````           ```````````````````               ````````````````   ```````````````              ```````````````````               ```````````````   ``````````````              ````````````````````              ```````````````
--



```

**Comment by bungle** [comment]
```

                               ```                 
                            ```````               
                          ````````````            
                        `````````````````         
                             ````````````         
                      ``````   ```````````        
                     `````````  ``````````        
                    ````````````  ````````        
                   ```````````````  ```           
                    ```````````````               
               ````  ````````````````             
             ````````  ````````````````           
          `````````````  ```````````````          
      ``````````````````   ```````````````        
    ``````````````````````  ````````````````      
   ````````````````````````   ````````````````    
 ````````````````````````       ```````````````   
```````````````                   ``````````````` 
`````````````   ``````````         ```````````````
````````````    ````````````         ```````````` 
``````````       ````````````          `````````` 
`````````         ````````````         `````````  
```

**Comment by bungle** [comment]
```
                               K                  
                             :KKKD                
                            ,KKKKKK               
                           KKKKKKKKK              
                          KKKKKKKKKKK             
                         KKKKKKKKKKKKKj           
                         KKKKKKKKKKKKKKK          
                        KKKKKKKKKKKKKKKKK         
                        :::::KKKKKKKKKKKK         
                             KKKKKKKKKKKL         
                       KKKKK  KKKKKKKKKKK.        
                      KKKKKKK  KKKKKKKKKKK        
                     DKKKKKKKE  KKKKKKKKKK        
                     KKKKKKKKK,  KKKKKKKKK        
                    KKKKKKKKKKK;  KKKKKKKK        
                    KKKKKKKKKKKK   KKKKKK         
                   KKKKKKKKKKKKKK  tKKKE          
                  ;KKKKKKKKKKKKKKK  KK:           
                   KKKKKKKKKKKKKKKK               
                 K  KKKKKKKKKKKKKKKE              
                KKt  KKKKKKKKKKKKKKK;             
              iKKKKt  KKKKKKKKKKKKKKK             
             EKKKKKK   KKKKKKKKKKKKKKK            
            KKKKKKKKK   KKKKKKKKKKKKKKK           
           KKKKKKKKKKK  DKKKKKKKKKKKKKKK          
       KKKKKKKKKKKKKKKK  DKKKKKKKKKKKKKKK         
      EKKKKKKKKKKKKKKKKK  KKKKKKKKKKKKKKKK        
     DKKKKKKKKKKKKKKKKKKK  KKKKKKKKKKKKKKKK       
     KKKKKKKKKKKKKKKKKKKKj  KKKKKKKKKKKKKKK       
    KKKKKKKKKKKKKKKKKKKKKK   KKKKKKKKKKKKKKK      
   KKKKKKKKKKKKKKKKKKKKKKKK  :KKKKKKKKKKKKKKK     
  KKKKKKKKKKKKKKKKKKKKKKKK    DKKKKKKKKKKKKKKK    
 EKKKKKKKKKKKKKKKKKKKKKKKi     GKKKKKKKKKKKKKKK   
 KKKKKKKKKKKKKKKKKKKKKKKK       KKKKKKKKKKKKKKKK  
KKKKKKKKKKKKKKK                  KKKKKKKKKKKKKKKK 
KKKKKKKKKKKKKKD                   KKKKKKKKKKKKKKK 
KKKKKKKKKKKKKK  KKKKKKKKKK         KKKKKKKKKKKKKKK
KKKKKKKKKKKKK  KKKKKKKKKKK,        .KKKKKKKKKKKKKL
KKKKKKKKKKKK    KKKKKKKKKKK.         KKKKKKKKKKKK 
KKKKKKKKKKK     KKKKKKKKKKKK         KKKKKKKKKKKK 
KKKKKKKKKKE      KKKKKKKKKKKK         KKKKKKKKKKK 
KKKKKKKKKK        KKKKKKKKKKKK         KKKKKKKKKK 
KKKKKKKKK         KKKKKKKKKKKK         KKKKKKKKKE 
KKKKKKKK          KKKKKKKKKKK:         KKKKKKKKK  
```

**Comment by bungle** [comment]
```
                                                 ╥▓▓,                           
                                              ╓▓▓▓▓▓▓▓▄                         
                                           ,▄▓▓▓▓▓▓▓▓▓▓▓▓▄                      
                                         ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓w                   
                                        ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓,                
                                      ,▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄,             
                                              ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀              
                                    ,,,,,,,,,   ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓              
                                   ╓▓▓▓▓▓▓▓▓▓▓    ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄            
                                  ▄▓▓▓▓▓▓▓▓▓▓▓▓▓    █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓            
                                 ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓            
                               ,▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄   `▓▓▓▓▓▓▓▓▓▀              
                              {▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄   └▓▓▓▓▀                 
                              `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓w   ▀                    
                          ,▄▄   └▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓µ                      
                        ╥▓▓▓▓▓▄   ╙▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓,                    
                     ╓▓▓▓▓▓▓▓▓▓▓w   ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓                   
                  ,▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓,   ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓                 
            ,,,,╓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓    ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄               
          ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄             
        ╓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄           
      ,▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄   `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓w         
     ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓    └▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓,       
   4▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀       ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      
 ╓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓           ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓    
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀                            ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌  
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█   ,,,,,,,,,,,,,,,              █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓   ,▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓,              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓^     ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓              `▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀        '▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄              ╙▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌ 
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓            █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄              ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  
▓▓▓▓▓▓▓▓▓▓▓▓▓▓              ╒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓              ╒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌  
```

**Comment by thibaultcha** [comment]
@bungle :joy:

**Pull request merged**
