### PR TITLE
spin out and upgrade Lambda plugin

### PR DESCRIPTION
**Pull request by Tieske**
The plugin now lives in its [own repo](https://github.com/Kong/kong-plugin-aws-lambda).

New features (see changelog):

* feat: if no credentiuals are provided, the plugin will automatically fetch EC2 or ECS credentials and use the AWS IAM roles retrieved for accessing the Lambda.
* feat: new option awsgateway_compatible to make the serialized request compatible with the AWS gateway format, making the plugin a drop-in replacement
* feat: new option skip_large_bodies to enable really large bodies (that have been cached to disk) to also be sent to the Lambda. Use with care!
* feat: added the ability to connect to the Lambda through a proxy

**Note on versioning**: the update was developed separately, hence the updates are in the changelog under `0.1.0`. After renaming the external plugin to `aws-lambda` the version was bumped to `3.0.0` to supersede the existing (internal Kong) version at `2.0.0`.

### CODE REVIEW

**Comment by Tieske** [comment]
CI fails on a LuaRocks error;

> Error: Build error: Failed installing kong/plugins/aws-lambda/v4.lua in /home/travis/install-cache/f99b7d5b0a5f6c9d070ff6ce527637ac/luarocks/lib/luarocks/rocks-5.1/kong/1.3.0-0/lua/kong/plugins/aws-lambda/v4.lua: The source and destination are the same files

**Comment by Tieske** [comment]
@murillopaula good catch! updated

**Comment by murillopaula** [comment]
@Tieske rebase current 'next' branch to make travis happy

**Comment by Tieske** [comment]
> rebase current 'next' branch to make travis happy

had already done so, but needed a few job-restarts to finally pass

**Comment by murillopaula** [comment]
@Tieske FYI the plugin's CI tests pass when pointing to the 'lambda' branch: https://github.com/Kong/kong-plugin-aws-lambda/pull/7

**Comment by kikito** [comment]
Hi, I have approved this change on this repo. However, I believe that some work is needed on the new aws-lambda repo. In particular, these:

```
* feat: if no credentiuals are provided, the plugin will automatically fetch EC2 or ECS credentials and use the AWS IAM roles retrieved for accessing the Lambda.
* feat: new option awsgateway_compatible to make the serialized request compatible with the AWS gateway format, making the plugin a drop-in replacement
* feat: new option skip_large_bodies to enable really large bodies (that have been cached to disk) to also be sent to the Lambda. Use with care!
( feat: added the ability to connect to the Lambda through a proxy
```

Seem to be missing.

**Comment by Tieske** [comment]
@kikito the changelog was updated (and merged)

**Pull request merged**
