### PR TITLE
refactor(pdk): serialize log msg with string.buffer

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

Use `string.buffer` to optimize string operation.

Here I simply replace table.insert and table.concat, but not sure the `serializers[n]`'s effect, so just keep them.

### Checklist

- [ ] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Comment by chobits** [comment]
I have reviewed the source code and confirmed that the new refactoring logic aligns with the original.

However I'm uncertain if this PR can improve the perfomance of string serialization. Its beneficial to run some simple tests on random string sets and compare the time consumption.

**Comment by zhongweiy** [comment]
Do we have any performance change data after this optimisation?

And the Jira ticket is missing in the PR message.

**Comment by chronolaw** [comment]
> Do we have any performance change data after this optimisation?
> 
> And the Jira ticket is missing in the PR message.

Not all PR need a Jira ticket, especially for some small changes.

**Comment by chronolaw** [comment]
> @chronolaw does this refactor provide a perf improvement?

I have no proper data to prove the improvement of performance, but I am sure it will be helpful for perf.
It seems that it is a little hard to test so small change of code, do we need to do this?

**Comment by zhongweiy** [comment]
I checked there are already a bunch of similar changes done before: 

https://github.com/Kong/kong-ee/pulls?q=is%3Apr+is%3Aclosed+author%3Achronolaw+string

Also there is similar discussion like https://github.com/Kong/kong/pull/11304#issuecomment-1671212708, which provides performance improvement like 5x time better when replacing table with string buffer in similar usage. 

Based on this, I feel it is OK to do similar replacement. @chronolaw Sorry for keeping the review process long and I'm a little bit conservative before checking the previous similar changes.

**Review by zhongweiy — APPROVED** [review]

**Review by chobits — APPROVED** [review]

**Pull request merged**
