### PR TITLE
perf(plugins-iterator): cache globals and replace iterators with iterator getters

### PR DESCRIPTION
**Pull request by bungle**
- perf(plugins-iterator): cache global plugins for faster execution
- perf(plugins-iterator): replace iterators with iterator getters

### CODE REVIEW

**Comment by bungle** [comment]
@ADD-SP, if you could benchmark this, it would be great, Thank you!

**Comment by fffonion** [comment]
spec#04-perf#01-rps#03-plugin_iterator_spec lua data combined
git#perf#plugins-iterator-2_#plugin_iterator_#global_only svg
git#master_#plugin_iterator_#global_only svg
git#perf#plugins-iterator-2_#plugin_iterator_#global_and_irrelevant svg
git#master_#plugin_iterator_#global_and_irrelevant svg

[svg files](https://github.com/Kong/kong/files/9652699/Archive.zip)

**Review by fffonion — APPROVED** [review]
Perf result shows great gain in performance. Code LGTM.
As this is a critical componenet, a second pair of eyes is appreciated.

**Comment by bungle** [comment]
One note: this needs to be carefully adapted on EE.

**Comment by ADD-SP** [comment]
I did two performance tests to confirm @fffonion 's result. I created a dummy plugin (on `rewrite`, `access`,  `certificate`, and `log`) and enabled it globally.

There are significant performance improvements.

## Fixed RPS

This test aims to measure the latency.

p90
p99
max

## Unlimited RPS

rps
p90
p99
max

**Pull request merged**
