### PR TITLE
fix(router) ignore failures on unexisting services when building router

### PR DESCRIPTION
**Pull request by ealogar**
### Summary

The router is being built querying all routes and iterating over each of them by searching the related service.
This is a potentially inconsistency as a service may be deleted during the process, the router won't be built and a 500 error will be returned.
Instead this error is ignored and the router is being built with the rest of routes. After all if a route is not found it will fail with a 404 (that it normal) or the request will be progressed as the service deletion was different.
The request won't be lost in most of the cases.

Moreover: when this process happend (without this fix) the  dao returned nil in err field and this was causing the log to fail:
```
2019/03/05 03:46:38 [error] 35#0: *40775 [kong] handler.lua:689 no router to route request (reason: /usr/local/share/lua/5.1/kong/runloop/handler.lua:89: attempt to concatenate local 'err' (a nil value)), client: 100.98.128.0, server: kong, request: "GET /my-route HTTP/1.1", host: "example.com"
```
What it's also a minor bug that is solved as well.

### Full changelog

* ignore failures when building routes and a service is deleted

### CODE REVIEW

**Comment by bungle** [comment]
This is a good reminder that we need to move these forward:
https://github.com/Kong/kong/pull/4202
https://github.com/Kong/kong/pull/4102

They only fix similar issues and then some. Our current target for "merging" them will be `1.2.0`. Let's keep this PR open as well as it is related, and perhaps we can include some of work done here to that upcoming work as well.

**Comment by bungle** [comment]
I marked it `for discussion` as it closely relates to other work already done in this area.

**Comment by thibaultcha** [comment]
We could pull this in 1.1.0 as a bugfix for the time being, taking a look at it.

**Comment by bungle** [comment]
Also, this touches a little bit the same place as well:
https://github.com/Kong/kong/pull/4286

**Comment by jeremyjpj0916** [comment]
Looks like the problem I have seen often has reared its ugly head again 😄 . Luckily @bungle has a great solution for it imo already tested and vetted around router/plugin map rebuild running in prod by us(me/Optum).

**Comment by bungle** [comment]
I think we may get some of the work to `1.1`. Things like:
1. use same db connection when rebuilding router
2. either cache services or preload them (caching feels more correct as the services may change between requests)
3. add a timer for rebuild but still leave the synchronous rebuilding on proxy time for worker consistency (make it configurable on `1.2` so that you don't affect proxy performance of p99)
4. do the atomic rebuilds of router and plugins map (if things change during build, e.g. because of paging and separate service selects, stop, and start again, as the paging cannot be trusted anymore).

**Comment by thibaultcha** [comment]
@bungle Will you propose a simplified version of your patches as well so we can compare approaches?

**Comment by ealogar** [comment]
I include a commit as the code was failing when a service is not found, I can reproduce locally deleting services. A Lua concat error was raised instead of building the router with the valid routes.
I will rebase it if you finally approve this.

**Comment by ealogar** [comment]
@thibaultcha @bungle I see that this problem may appear in release 1.1.0 released today, are you planning in adding this or a different approach to solve it ?

**Pull request closed without merging**
