### PR TITLE
feat(jwt) support RS384 algorithm

### PR DESCRIPTION
**Pull request by dlouzan**
### Summary

Add support for RS384 signature algorithm per [rfc7518](https://tools.ietf.org/html/rfc7518) to JWT plugin.

### Full changelog

* Implement support for verifying RS384 signed JWTs
* Add related tests

🛠 with ❤ at [Siemens](https://www.siemens.com)

/cc @bufferoverflow

### CODE REVIEW

**Review by bungle — APPROVED** [review]

**Comment by bungle** [comment]
@dlouzan,

Very nice PR, as it is a `feat` can you please rebase it to `next`. Unfortunately at this point of time it means that it will go to `2.3.0`.

**Comment by bungle** [comment]
This PR just needs rebasing to `next`, otherwise it is ok. @dlouzan can you please do that, and change the target to `Kong:next` on this PR.

**Comment by dlouzan** [comment]
@bungle Thanks for the prompt response!

I was hoping that this could make it to 2.2 since it had no incompatible changes, but I realize now that you guys are already in beta mode for 2.2 :thumbsup: I'll take care of rebasing on top of `next` today.

**Comment by dlouzan** [comment]
@bungle Just pushed and changed the base branch 🚀

**Comment by bungle** [comment]
> @bungle Thanks for the prompt response!
> 
> I was hoping that this could make it to 2.2 since it had no incompatible changes, but I realize now that you guys are already in beta mode for 2.2 👍 I'll take care of rebasing on top of `next` today.

Tell me about it, ;-). But don't worry, we try to get new releases out often, so it should be in release in a next few months.

**Comment by dlouzan** [comment]
@bungle Thanks for the merge guys!

Related question: can you think of an easy way for us to apply the updated plugin on top of the stable build without much pain? This is currently a must for one of our integrations (the auth server only supports RS384 for access tokens), and we would like to at least run some longer tests before waiting for 2.3, which based on previous releases will take 2 or 3 months.

The approach for testing this MR was basically to build our own image based on the branch sources, but ofc this will be more difficult to keep updated 😅

**Comment by bufferoverflow** [comment]
This is more a fix then a feature as it adds a missing algorithm. I wonder why it takes a few months until next release.

**Comment by dlouzan** [comment]
@bungle I haven't seen this feature mentioned on 2.3.0-beta1 changelog. Has this PR been deployed on that release and it is missing on the changelog, or it was intentionally left out?

Just asking because we were waiting for 2.3 to deploy the jwt support internally :bow:

**Comment by dlouzan** [comment]
2.3 was released yesterday and I see no mention of this in the release notes. Assuming it was picked since it's on master 🤷

**Pull request merged**
