### PR TITLE
fix(db) entity checks on put and cassandra upsert checks

### PR DESCRIPTION
**Pull request by bungle**
### Summary

It fixes this call (maybe something else too):
```
http put :8001/consumers/test
```

### CODE REVIEW

**Comment by hishamhm** [comment]
@bungle what is expected to happen with `http put :8001/consumers/foo username=bar` (if `foo` exists and if `foo` doesn't exist)?

**Comment by bungle** [comment]
You cannot change url with `PUT`.

**Comment by bungle** [comment]
You have to use `http put :8001/consumers/<uuid> username=bar`.

**Comment by hishamhm** [comment]
@bungle do we have test cases to verify these two scenarios fail (with consistent error messages in both strategies)? if not, it would be a good idea to add to this PR.

**Comment by bungle** [comment]
If we want to have this included in release then we are running out of time to add anything.

**Comment by hishamhm** [comment]
@bungle I ran the queries locally (with your two PRs applied), and `http put :8001/consumers/foo username=bar` gives a 200 (upserts and ignores `username=bar`) in both Postgres and Cassandra.

Is that the correct behavior or should it instead give an error?

**Comment by bungle** [comment]
@hishamhm yes, put ignores stuff in params so that it stays idempotent.

**Comment by bungle** [comment]
For example:
`PUT /consumers/bob username=jack` <- the username cannot be changed because that would change the the URI as well.

`PATCH /consumers/bob username=jack` <-- should work

`PUT` is always a full replace, `PATCH` is partial, though you can update all parameters.

**Pull request closed without merging**
