### PR TITLE
feat(config) enable reading credentials from files

### PR DESCRIPTION
**Pull request by Tieske**
Allows both Cassandra and PostgreSQL username and passwords
to be read from a file. To make cloud configuration a bit
friendlier for secret managers.

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Do we have a specific supported distribution (k8s, mesos, etc) where this would be more advantageous over using an environmental variable? In talking to @thefosk I've heard that the latter (an env var) is preferred.

**Comment by Tieske** [comment]
it's about providing options

**Comment by thibaultcha** [comment]
Not a big fan of adding options without a high demand from the user base... This adds maintenance overhead on our shoulders and create a lot of additional configuration properties which overall adds a lot of boilerplate to the configuration file... Speaking of the configuration file, I have trouble understanding the benefits of writing those credentials to a separate file (instead of the configuration file itself). In fact, I do not know of any other major piece of software doing this - credential values are generally accepted from a configuration file or a an environment variable. Do you have any example of this (and benefits) from another project?

Additionally, this can easily lead to user confusion and additional support load when we take permissions into account: the default NGINX user is `nobody`, and I can easily see users making such credential files with restricted permissions, and hitting a permission denial once NGINX starts because the `nobody` user would not be allowed to read those files. That kind of behavior not only adds maintenance overhead, but also documentation, and support... And where do we draw the line? Do each credential property need to be specifiable from a file now? Even the ones we will add in the future? What about credential values stored in plugins configurations, like a Redis password?

Also, the boolean flags enabling/disabling that behavior are to put it simply... cumberstone. A simple set/unset condition should be good enough to activate or not this behavior - but that is a minor issue, I am personally more concerned about bigger implications detailed above.

**Comment by Tieske** [comment]
There have been user requests for this in the past. As mentioned in the OP goal: make Kong a better citizen in cloud environments

Specific use case: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

Regarding the flag; I started by adding an info type, either "credential" or "file". In the former case the existing fields would hold the credentials, in the later they would hold file names. But since the password is a special case (occasionally hiding it and not logging etc) this became weird quickly. Hence the alternative with duplicate config fields.

Any ideas how to improve on this?

**Comment by Tieske** [comment]
closing this for now. If required, can be revisited later.

**Pull request closed without merging**
