### PR TITLE
Release: 2.1.0

### PR DESCRIPTION
**Pull request by hutchic**

### CODE REVIEW

**Comment by carnei-ro** [comment]
In the changelog it says that includes https://github.com/Kong/kong/pull/5831 but function load_upstreams_dict_into_memory() from kong/runloop/balancer.lua does not have the changes. Is it correct?!
Tested with rpm from https://dl.bintray.com/kong/kong-prerelease/centos/7/

I also had to install zlib-devel.

**Comment by gszr** [comment]
@carnei-ro, thanks for reporting. Are you able to reproduce the issue in the alpha?

**Comment by carnei-ro** [comment]
@gszr The issue only appears when I run Kong in production environment (high throughput) (CentOS at AWS) using UpStreams. I can't reproduce it easily and I'm waiting for the confirmation to roll out the version to prod.

**Comment by carnei-ro** [comment]
@gszr any updates on this? Will the fix #5831 will be included in 2.1.0 ?

**Comment by gszr** [comment]
hey @carnei-ro Have you been able to confirm whether the issue persists in 2.1-alpha1? The fix you linked was specific to `master`, hence why it didn't make it into 2.1-alpha1. If the issue is still reproducible in 2.1-alpha1, the team will look into it. Thanks!

**Comment by carnei-ro** [comment]
@gszr we could reproduce once, I've recorded the to explain the scenario https://www.youtube.com/watch?v=w69NekUyRCk

**Comment by gszr** [comment]
Thank you so much, @carnei-ro, this is going to help. We are actively working on this issue.

**Comment by gszr** [comment]
Hey @carnei-ro,

We've verified the issue _is_ reproducible on 2.0.4 (and below), but _not reproducible_ on 2.1.0-alpha1. Here are the steps we took:

1. Run a Kong 2.0.4:
```
docker run -ti -d --name kong -e "KONG_DATABASE=off" \ -e "KONG_PROXY_LISTEN=0.0.0.0:8000" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" -e KONG_PROXY_ERROR_LOG=/logs/error.log -e KONG_PROXY_ACCESS_LOG=/dev/null \ -p 8000:8000 \ -p 8001:8001 \ -v "$PWD/logs:/logs" \ kong:2.0.4
```

2. Start a shell loop sending POST requests to /config:
```
for i in $(seq 1 500); do http :8001/config config=@../misc/kong.yml; done
```

(Find kong.yaml [here](https://gist.github.com/gszr/ede8ec1c8bc7727a30f2188b52372cc1)).

3. In a separate terminal window, send requests to the proxy port:
```
for i in $(seq 1 5000); do curl -s -o /dev/null -w "%{http_code}\n" localhost:8000; done
```

This will print the status code of all requests; lots of 503s will be seen. The logs in logs/error.log will contain errors like the following:
```
2020/06/01 15:52:18 [error] 22#0: *19380 [lua] balancer.lua:929: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)upstream1:(na) - cache-miss","upstream1:33 - cache-hit/dns server error: 3 name error","upstream1:1 - cache-hit/dns server error: 3 name error","upstream1:5 - cache-hit/dns server error: 3 name error"], client: 172.17.0.1, server: kong, request: "GET / HTTP/1.1", host: "localhost:8000"
```

If the same is attempted against **2.1.0-alpha1** (or with Kong master branch), **no 503s will occur**.

Note that the issue is also not reproducible in Kong `master`, following the fix you linked.

**Comment by carnei-ro** [comment]
@gszr Do you think it was lucky to not reproduce with 2.1.0-alpha1 (it does not include the fix), or it was, indeed, fix in that version too?

**Comment by gszr** [comment]
@carnei-ro I have personally spent quite some time attempting to reproduce (applied the same steps to 3 different versions -- 2.0.2, 2.0.4, and 2.1-alpha1) and the issue isn't reproducible in 2.1-alpha. The issue is pretty easily/quickly reproducible in 2.0.x with the steps I posted above (no need to leave it running for hours or so). Given the balancer code in 2.1 contains many changes, I'm confident the issue is fixed in it. That said, if you manage to reproduce it in alpha1, please do report back!

**Pull request closed without merging**
