### PR TITLE
(Grammar Changes) Update bug_report.yaml

### PR DESCRIPTION
**Pull request by ArjunSharda**
### Summary

This will fix some grammatical issues potentially making the wording more easier to read.

### Full changelog

* This changes wording in the bug_report.yaml file as some grammar is not correct.

### CODE REVIEW

**Review by fffonion — APPROVED** [review]

**Comment by ArjunSharda** [comment]
Please review @kikito

**Review by dndx — APPROVED** [review]

**Comment by ArjunSharda** [comment]
Please merge @fffonion as I can't and I have updated to the latest branch

**Comment by ArjunSharda** [comment]
Please merge @dndx as I can't.

**Comment by hbagdi** [comment]
@gszr Could you please merge this one in?

**Pull request merged**
