### PR TITLE
chore(key-auth): test key-auth ttl on Hybrid mode (FTI-4512)

### PR DESCRIPTION
**Pull request by outsinre**
### Summary

Just leave a note here.

DO NOT MERGE!

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[FTI-4512]_

[FTI-4512]: https://konghq.atlassian.net/browse/FTI-4512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bungle** [comment]
@outsinre jut a note, I think the fix should land here:
https://github.com/Kong/kong/blob/master/kong/db/strategies/off/init.lua

So when reading data, it should ignore `ttl'd items.

**Comment by hbagdi** [comment]
@outsinre Any blockers here? This is pretty important to fix as it can lead to security incidents otherwise.

**Comment by outsinre** [comment]
> @outsinre Any blockers here? This is pretty important to fix as it can lead to security incidents otherwise.

@hbagdi , I will discuss with in today's standup meeting to discuss ideas and then the design.

**Comment by hbagdi** [comment]
@outsinre Any update?

**Comment by hbagdi** [comment]
Closing because of lack of activity. We would like to accept this contribution if anyone wishes to pick this back up.

**Pull request closed without merging**
