### PR TITLE
chore(build): downgrade dependencies versions

### PR DESCRIPTION
**Pull request by Water-Melon**
### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Review by chobits — APPROVED** [review]

**Comment by fffonion** [comment]
we need a new tag that only has this https://github.com/Kong/lua-kong-nginx-module/pull/83

**Comment by Water-Melon** [comment]
> we need a new tag that only has this [Kong/lua-kong-nginx-module#83](https://github.com/Kong/lua-kong-nginx-module/pull/83)

lua-kong-nginx-module `0.2.1` does not have directory `src/ssl`.

**Comment by Water-Melon** [comment]
full build test:
https://github.com/Kong/kong/actions/runs/9627113146?pr=13282
https://github.com/Kong/kong/actions/runs/9627113144?pr=13282

**Comment by fffonion** [comment]
i have created https://github.com/Kong/lua-kong-nginx-module/pull/92 and `0.2.1-sr1` tag in case.

**Review by fffonion — APPROVED** [review]

**Comment by Water-Melon** [comment]
> i have created [Kong/lua-kong-nginx-module#92](https://github.com/Kong/lua-kong-nginx-module/pull/92) and `0.2.1-sr1` tag in case.

yeah, I saw it. I have modified `.requirements` to bump lua-kong-nginx-module to `0.2.1-sr1`.

**Review by locao — APPROVED** [review]

**Pull request merged**
