### PR TITLE
tests(helpers): support ldoc generation

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

KAG-5333, support ldoc generation.
- edit `config.ld`, add directory `./details` and `merge=true`
- add `@module` header for separated test modules

### Checklist

- [ ] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Comment by chronolaw** [comment]
@Tieske , could you take a look? thanks.

**Comment by Tieske** [comment]
added some minor fixes.

what strikes me is that the section "Custom assertions" contains a ton of unrelated stuff, eg. `start_kong` used to be located under "shell helpers"?

**Comment by Tieske** [comment]
fyi: the `spec/renderdocs.sh` scripts can be used to re-render docs on the fly while editing them.

**Comment by chronolaw** [comment]
> added some minor fixes.
> 
> what strikes me is that the section "Custom assertions" contains a ton of unrelated stuff, eg. `start_kong` used to be located under "shell helpers"?

We could fix these concerns later, now we will focus on module splitting.

**Review by ProBrian — APPROVED** [review]

**Review by Water-Melon — APPROVED** [review]

**Review by chobits — APPROVED** [review]

**Pull request merged**
