### PR TITLE
Fix/0.14.x plugins iterator

### PR DESCRIPTION
**Pull request by kikito**

### CODE REVIEW

**Comment by hishamhm** [comment]
This will not work for 1.0 because kong.dao will be gone.

**Comment by kikito** [comment]
You mean it will be `nil`, right? I'm counting on that.

**Comment by kikito** [comment]
Oh you mean `kong.dao` *itself* will be nil so `kong.dao.plugins` will throw an error. I added an extra check for that. Thanks!

**Comment by kikito** [comment]
Closing this down in favor of #3898

**Pull request closed without merging**
