### PR TITLE
chore(tests) tests renamed to have no sequence gaps

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Renames test suite files and folders to have a sequence without gaps, also renames `new-dao` to just `db`.

### CODE REVIEW

**Comment by bungle** [comment]
Question, If we want to merge this, should we merge it to `next` or `master` (currently based on `master`, but I can `rebase` it if needed)?

**Comment by kikito** [comment]
@bungle I think we should do this in both simultaneously. Or first in master and then rebase master into next.

**Comment by thibaultcha** [comment]
I just merged master into next to synchronize those changes.

**Comment by bungle** [comment]
I guess many of the current PRs need to be rebased, but well, that was expected.

**Pull request merged**
