### PR TITLE
hotfix(balancer) invalidate cache when creating upstreams

### PR DESCRIPTION
**Pull request by hishamhm**
Make sure that cache for the overall list of upstreams is invalidated when an individual upstream is created.

Includes a regression test.

### CODE REVIEW

**Comment by hishamhm** [comment]
@thibaultcha Indeed, renaming the upstreams is causing caching issues. I've got a regression test and a fix handy, but I'm testing some more cases. Should I add to this PR or open a second one?

**Comment by thibaultcha** [comment]
I think it would be fine to update this PR!

**Comment by thibaultcha** [comment]
Manually merged for the 0.12 branch history!

**Comment by hishamhm** [comment]
@thibaultcha thanks! for the record, the earlier CI failures were Travis hiccups -- some of the jobs failed to start. I restarted them and they ran green.

**Comment by hishamhm** [comment]
@thibaultcha thanks! for the record, the earlier CI failures were Travis hiccups -- some of the jobs failed to start. I restarted them and they ran green.

**Pull request closed without merging**
