### PR TITLE
chore(ci) run CI against all branches / PR's

### PR DESCRIPTION
**Pull request by hutchic**
Need more discussion or results: do we need to run CI against all branches or only PR's and specific branches?

### CODE REVIEW

**Comment by javierguerragiraldez** [comment]
i don't think we need all tests all the time (could be waay wrong, ofc).  i'm ok with having to push a few buttons to get a PR tested.  but if i have to edit some yaml to get something to work, i can guarantee i'll get it wrong 80-90% of the time.

TL:DR:
- less aggresive automation: +0
- need some human step before working: 0
- editing files to get things done: -1

**Comment by hutchic** [comment]
a draft PR's would kick off a PR. The motivation is we very seldom care about the head of a branch more oft then not the PR merge is the only thing that matters

**Comment by hishamhm** [comment]
> a draft PR's would kick off a PR. The motivation is we very seldom care about the head of a branch more oft then not the PR merge is the only thing that matters

my 2 cents: I _very often_ care about the head of a branch. For anything substantial, I try to only open a PR when the head of a branch is green. :)

**Comment by gszr** [comment]
> > a draft PR's would kick off a PR. The motivation is we very seldom care about the head of a branch more oft then not the PR merge is the only thing that matters
> 
> my 2 cents: I _very often_ care about the head of a branch. For anything substantial, I try to only open a PR when the head of a branch is green. :)

I second this. When developing I rarely run more than a few spec files locally; most often, I push a branch and watch tests progress before opening a PR.

**Comment by dndx** [comment]
Merged, thanks everyone and @hutchic for the PR!

**Pull request merged**
