### PR TITLE
refactor(router) use tablepool to improve router

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

Inspired by #9036, I introduced `tablepool` in atc router.
I think it may be some help for performance.

### Full changelog

* use `tablepool` to reduce small table object usage

### CODE REVIEW

**Review by Suika-Kong — COMMENTED** [review]
Instead of using a pool, we could just reuse the same table all the time.

**Comment by chronolaw** [comment]
> Instead of using a pool, we could just reuse the same table all the time.

Yes, it is true, but we still need to clear items in the reused table. `tablepool` did these for us.

**Comment by fffonion** [comment]
I agree with @Suika-Kong , seems some long-lived tables is cleaner, we can just do `table.clear` instead of `release_table`, how do you think @chronolaw ?

**Comment by chronolaw** [comment]
> I agree with @Suika-Kong , seems some long-lived tables is cleaner, we can just do `table.clear` instead of `release_table`, how do you think @chronolaw ?

OK, I will reimplement this feature.

**Review by dndx — APPROVED** [review]

**Pull request merged**
