### PR TITLE
feat(pdk): add authentication context

### PR DESCRIPTION
**Pull request by vm-001**
### Summary

Introduces authentication context.

For the authentication plugins that not only require providing the key(password) but also a username, like `basic-auth`, Kong set the given_username into `ngx.ctx.authentication_context`. A typical use case is that users can log or inject the given_username into http log event when key(password) and username are invalid. 

For example:
```yaml
plugins:
- name: basic-auth
- name: http-log
  config:
    http_endpoint: ""
    method: "POST"
    custom_fields_by_lua:
      authentication_context.username: "return kong.client.get_authentication_context() and kong.client.get_authentication_context().username"
```

### Checklist

- [x] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference
FTI-5281

### CODE REVIEW

**Comment by bungle** [comment]
Hi @vm-001, we looked this together with @hanshuebner. To recap what discussed.

*Current State*

1. kong sets ngx.ctx.authenticated_consumer to Consumer entity on *successful authentication* (either by credential to Consumer mapping or perhaps by OIDC Claim / SAML Attribute mapping to Kong Consumer).
2. kong sets ngx.ctx.authenticated_credential to credential (of varying types) or in case of say OpenID Connect it just sets it to `{ id = tostring(credential_value) }` (where credential_value is value found with `credential_claim` which defaults to standard `sub`). Again this happens on *successful authentication only*.
3. Plugins can set `ngx.ctx.authenticated_groups` too.
4. Plugins usually also set headers for these `X-Consumer-ID`, `X-Consumer-Username`, `X-Consumer-Custom-ID`, `X-Credential-Identifier`, `X-Authenticated-Groups`, `X-Consumer-Groups`.
5. Usually the plugins also remove the credentials given from the request (the `hide_credentials` config).

*The PR Proposal*

The PR here is about storing the user given credentials. The problem with Kong Credentials and User given credentials is that they are not standardized. E.g. in this PR we see this data added to context:
```
{
   username = "...",
}
```

Well what if there is key auth? Do we really want to set:
```
{
   key = "valid or invalid key",
}
```

Or OIDC:
```
{
   access_token = "<jwt>",
}
```

And then log the valid and invalid credentials or part of them? It may also be problematic on privacy side and this can create a foot gun where things like email addresses get logged and collected to places where they should not be logged.

I think the idea is fine, but I think we need to think this further. We are not too happy how it currently works, especially the `ngx.ctx.authenticated_credential` and how it gets used to run authentication plugins in `OR`  fashion, and how the `type` of it is basically unknown to anything else than the one that sets it. The same unknown type problem is here with authentication context. It is hard to use by any other code, even the example:

```
authentication_context.username: "return kong.client.get_authentication_context() and kong.client.get_authentication_context().username"
```

Makes assumptions that there is `username` and when there can be many authentication plugins it gets more complicated. Thus I think we need to think this a bit more.

The PR makes changes to all the plugins, but to make it really usable across the board, we would need to make changes to perhaps all the authentication plugins.

Further thinking is it possible to standardize authentication context:
```
{
   identifier: my-username
   method: basic-auth
}
```

```
{
   identifier: hash of give key?
   method: key-auth
}
```

```
{
   identifier: <client-id|username|opaque-token|jwt-token|auth-code...>
   method: openid-connect
}
```

When it is ok to make these available, what are the use cases, should they be filtered / sanitized before say logging them or even before putting them in context. Thus we want to leave it on a table to let this idea mature a bit.

@hanshuebner, do you have something to add?

**Comment by hanshuebner** [comment]
I think the key point of this PR is that the credential information that was used in an authentication attempt is stored in the `authentication_context` before the actual authentication runs.  This ensure that the information is available in the `log` phase, even if the authentication fails.  For many use cases, it would also be possible to extract the authentication information from the request header in the `log` phase.  I think for the specific use case that is being addressed by this PR (and the FTI/A-HA tickets), the cost of the implementation (increased request context size and maintenance burden of the extra `authentication_context`, which only serves this specific purpose) is too high.

As @bungle described, our authentication related data structures and mechanisms are already somewhat difficult to understand and maintain.  We'd like to change that, but that is probably not going to happen very soon.  For the logging use case, I would suggest a simpler approach that does not require a change in how authentication is handled in Kong overall.

**Comment by jschmid1** [comment]
This PR is set for the 3.5.0 milestone but didn't receive updates in the recent past. @vm-001 please remove the milestone if you think this won't make it.

**Comment by kikito** [comment]
We discussed this PR in PR Queue Review. I'm removing it from the 3.5 milestone so we can design this feature better (with a design doc).

**Pull request closed without merging**
