### PR TITLE
feat/plugins-rate-limiting limit by path

### PR DESCRIPTION
**Pull request by taotao2014**
### Summary

plugins-rate-limiting limit by path

### CODE REVIEW

**Comment by locao** [comment]
Hi @taotao2014, thanks for your submission!

I believe those changes to the PDK are not needed by this feature, right? Could you split these features in two different PRs, please?

We are still discussing if it is interesting to expose the balancer details to the PDK, but rate-limiting by path sounds like a nice feature.

**Comment by taotao2014** [comment]
> Hi @taotao2014, thanks for your submission!
> 
> I believe those changes to the PDK are not needed by this feature, right? Could you split these features in two different PRs, please?
> 
> We are still discussing if it is interesting to expose the balancer details to the PDK, but rate-limiting by path sounds like a nice feature.

Thank you @locao , the feature has been split.

feat/plugins-rate-limiting by path #6216

https://github.com/Kong/kong/pull/6216

**Comment by fairyqb** [comment]
update #6234

**Comment by kikito** [comment]
I am closing this one since the change mentioned on the title was merged in #6286 . If you want to add that extra function to the PDK, please send a different PR. Thanks!

**Pull request closed without merging**
