### PR TITLE
fix(worker_event): send large payload

### PR DESCRIPTION
**Pull request by liverpool8056**
### Summary

There is a limit for the size of the payload when using worker_event lib. This limit prevent `too big` payload from being published through worker_event. This PR provide a solution for this case. The payload will be sent in serval smaller frame when the payload exceeds the limit, and they will be assembled at the side of the receiver.

### Checklist

- [x] The Pull Request has tests
- [x] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

FTI-4963

### CODE REVIEW

**Comment by chronolaw** [comment]
It seems to be a complex solution? should we increase the limitation of lua-resty-events?
For example, increase to `2^24 - 1`, i.e. 16MB?

**Comment by liverpool8056** [comment]
@chronolaw glad to see that, so set this as a draft

**Comment by chronolaw** [comment]
PR https://github.com/Kong/lua-resty-events/pull/37 increase the limitatioin to 16MB, do you think it is enough?

**Comment by chronolaw** [comment]
PR #11203 will replace this PR, waiting the final decision.

**Comment by liverpool8056** [comment]
We made a decision to add a new parameter for specifying the limit in worker_events, referring to https://github.com/Kong/lua-resty-events/pull/37, this PR can be closed.

**Pull request closed without merging**
