### PR TITLE
tests(*): Fixed typo error recieve ->receive

### PR DESCRIPTION
**Pull request by thephenix4**
### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Review by chronolaw — APPROVED** [review]

**Review by mayocream — APPROVED** [review]

**Comment by bungle** [comment]
This needs also be fixed in code.

**Review by bungle — CHANGES_REQUESTED** [review]
The same typo os on kong.tools.wrpc.future.lua

**Comment by bungle** [comment]
> The same typo os on kong.tools.wrpc.future.lua

also in changelog and wrpc.proto

**Comment by chronolaw** [comment]
I have created a related PR #9486.

**Comment by chronolaw** [comment]
Thanks for your contribution. We have created a same PR (#9486) to fix these typos. Because that PR includes the same changes as this PR, I need to close this PR.

Thank you again.

**Pull request closed without merging**
