### PR TITLE
Add/change test helpers to facilitate db-less plugin testing

### PR DESCRIPTION
**Pull request by Tieske**
Here's an example of a test file adjusted to also run db-less tests, using the helpers from this PR:
https://github.com/Kong/kong-plugin/compare/dbless?expand=1

The 2nd commit in this PR fixes some ldoc related issues in the helpers file, please review commits one-by-one

BTW; this should land in 2.2

ping @mikefero @kidd

### CODE REVIEW

**Comment by mikefero** [comment]
The helper changes look great, but there is currently an issue in CI when using `KONG_TEST_DATABASE=off`, the below patch doesn't fix the issue but it does simplify and correct the test based on these helper changes.

```diff
diff --git a/spec/02-integration/05-proxy/02-router_spec.lua b/spec/02-integration/05-proxy/02-router_spec.lua
index a9197ccd..014771e9 100644
--- a/spec/02-integration/05-proxy/02-router_spec.lua
+++ b/spec/02-integration/05-proxy/02-router_spec.lua
@@ -65,27 +65,6 @@ local function insert_routes(bp, routes)
     routes[i] = route
   end
 
-  if bp.done then
-    local declarative = require "kong.db.declarative"
-
-    local cfg = bp.done()
-    local yaml = declarative.to_yaml_string(cfg)
-    local admin_client = helpers.admin_client()
-    local res = assert(admin_client:send {
-      method  = "POST",
-      path    = "/config",
-      body    = {
-        config = yaml,
-      },
-      headers = {
-        ["Content-Type"] = "multipart/form-data",
-      }
-    })
-    assert.res_status(201, res)
-    admin_client:close()
-
-  end
-
   return routes
 end
 
@@ -118,7 +97,7 @@ local function remove_routes(strategy, routes)
 end
 
 for _, b in ipairs({ false, true }) do enable_buffering = b
-for _, strategy in helpers.each_strategy() do
+for _, strategy in helpers.all_strategies() do
   describe("Router [#" .. strategy .. "] with buffering [" .. (b and "on]" or "off]") , function()
     local proxy_client
     local proxy_ssl_client
@@ -149,6 +128,7 @@ for _, strategy in helpers.each_strategy() do
         database = strategy,
         plugins = "bundled,enable-buffering",
         nginx_conf = "spec/fixtures/custom_nginx.template",
+        declarative_config = helpers.write_declarative_config(strategy),
       }, nil, nil, fixtures))
     end)
 
@@ -1994,6 +1974,7 @@ for _, strategy in helpers.each_strategy() do
         nginx_worker_processes = 4,
         plugins = "bundled,enable-buffering",
         nginx_conf = "spec/fixtures/custom_nginx.template",
+        declarative_config = helpers.write_declarative_config(strategy),
       }))
     end)
 
```

**Comment by Tieske** [comment]
seems to me the tests are flaky, here's what I get locally;
```
vagrant@ubuntu1604:/kong$ git status
On branch dbless
Your branch is up-to-date with 'origin/dbless'.
nothing to commit, working directory clean
vagrant@ubuntu1604:/kong$ bin/busted  spec/02-integration/05-proxy/02-router_spec.lua
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
1332 successes / 0 failures / 0 errors / 0 pending : 93.289031 seconds
vagrant@ubuntu1604:/kong$
```

**Comment by Tieske** [comment]
@mikefero removed a little bit of magic, should go green now. Adds a bit more code to the test files, but probably easier to understand since there is less magic.

(and most of all; it works 😄 )

**Review by mikefero — APPROVED** [review]
Great work!!!

I ran through a test with a modified test for the rate-limiting-advanced plugin and everything worked as it should.

**Review by kikito — APPROVED** [review]

**Review by locao — APPROVED** [review]

**Comment by hishamhm** [comment]
```
--
--       -- when calling "get_db_utils" with "strategy=off", we still use
--       -- "postgres" so we can write the test setup to the database.
--       local bp = helpers.get_db_utils(
--                      strategy == "off" and "postgres" or strategy,
--                      nil, { PLUGIN_NAME })
```

@Tieske  I'm seeing this late, but as far as I remember, this convolution of forcing "postgres" and writing things to a database to produce a declarative config should not be necessary in order to test DB-less. When you run `get_db_utils` on DB-less it produces you a special subclass of `bp` which buffers `inserts` into memory, and then `start_kong` auto-detects that, writes a declarative config file and starts kong. This is how the balancer tests all run on DB-less without having to write special-case DB-less code, as long as they follow the pattern of setting up in the following order:

1. `get_db_utils`
2. `bp[entity].insert`
3. `start_kong`

which many tests before didn't, as they would often `bp[entity].insert` after starting Kong, so that needed to be changed in the tests. But you won't find a lot of `strategy == "off"` tests in the DB-less tests.

There's a second abstraction layer on the balancer tests nowadays (added in order to test them with multiple workspaces on Enterprise using a single test suite (it used to be duplicated before)), so the balancer tests nowadays don't work as an easy-to-read example of DB+DB-less tests.

I don't know if any of the plugin test suites in the core are enabled for DB-less (some plugins are exercised as part of the DB-less core tests); if not, they should be, and it shouldn't be necessary to add DB-less specific scaffolding to the tests themselves (other than adding a `#db` hashtag to disable things such as PATCH Admin API tests), the helpers should make that transparent (and without needing to go through the DB to test DB-less). If that didn't work, there's either a documentation problem on how to do it, or there was a bug in the helpers themselves.

**Comment by Tieske** [comment]
@hishamhm afaik the `bp[entity].insert` will only work for Kong native entities. For custom DAO's they are not available, right? So in those cases your scenario above doesn't work?

**Pull request merged**
