### PR TITLE
chore(tests): remove hardcoded dns resolver in tests

### PR DESCRIPTION
**Pull request by fffonion**
FTI-3133

### CODE REVIEW

**Comment by fffonion** [comment]
@hanshuebner I ran a `grep` over `spec/` and found those are relevant and can be removed. 
`8.8.8.8` also exists in multiple tests but I checked them one by one and looks they are placeholders
and no DNS queries are actually sent.
```
spec/01-unit/21-dns-client/01-utils_spec.lua:nameserver 8.8.8.8
spec/01-unit/21-dns-client/01-utils_spec.lua:nameserver 8.8.8.8:1234 ; this one has a port number (limited systems support this)
spec/01-unit/21-dns-client/01-utils_spec.lua:      assert.is.same({ "8.8.8.8", "2602:306:bca8:1ac0::1", "8.8.8.8:1234" }, resolv.nameserver)
spec/01-unit/21-dns-client/01-utils_spec.lua:nameserver 8.8.8.8
spec/01-unit/21-dns-client/01-utils_spec.lua:nameserver 8.8.8.8
spec/01-unit/21-dns-client/01-utils_spec.lua:              "nameserver 8.8.8.8 ",
spec/01-unit/21-dns-client/03-client_cache_spec.lua:        nameservers = { "8.8.8.8" },
spec/01-unit/21-dns-client/03-client_cache_spec.lua:        nameservers = { "8.8.8.8" },
spec/01-unit/21-dns-client/03-client_cache_spec.lua:        nameservers = { "8.8.8.8" },
spec/01-unit/21-dns-client/03-client_cache_spec.lua:        nameservers = { "8.8.8.8" },
spec/01-unit/21-dns-client/02-client_spec.lua:          nameservers = { "8.8.8.8:53" },
spec/01-unit/21-dns-client/02-client_spec.lua:            nameservers = { "8.8.8.8:53" },
spec/01-unit/21-dns-client/02-client_spec.lua:            nameservers = { "8.8.8.8:53" },
spec/01-unit/21-dns-client/02-client_spec.lua:            nameservers = { "8.8.8.8:53" },
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:              "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:            "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:          "nameserver 8.8.8.8",
spec/01-unit/21-dns-client/02-client_spec.lua:        "nameserver 8.8.8.8",
spec/01-unit/03-conf_loader_spec.lua:        dns_resolver = "8.8.8.8:53"
spec/01-unit/03-conf_loader_spec.lua:        dns_resolver = "8.8.8.8,1.2.3.4:53,::1,[::1]:53"
spec/01-unit/09-balancer/04-round_robin_spec.lua:        "nameserver 8.8.8.8"
spec/01-unit/09-balancer/04-round_robin_spec.lua:        { name = "getkong.test", address = "8.8.8.8" },
spec/01-unit/09-balancer/04-round_robin_spec.lua:          "nameserver 8.8.8.8"
spec/01-unit/09-balancer/03-consistent_hashing_spec.lua:        "nameserver 8.8.8.8"
spec/01-unit/09-balancer/01-generic_spec.lua:          "nameserver 8.8.8.8"
spec/01-unit/09-balancer/02-least_connections_spec.lua:        "nameserver 8.8.8.8"
spec/01-unit/04-prefix_handler_spec.lua:        dns_resolver = { "8.8.8.8", "8.8.4.4" }
spec/01-unit/14-dns_spec.lua:    nameservers = { "8.8.8.8" },
```

Let me know if this is covering your original thought : )

**Comment by hanshuebner** [comment]
> 8.8.8.8 also exists in multiple tests but I checked them one by one and looks they are placeholders and no DNS queries are actually sent.

I would suggest using an address different from 8.8.8.8 so that the address can never accidentally used for lookups.  198.51.100.0 would be a good address, at it is in a reserved test address block that will never be allocated ([RFC5737](https://datatracker.ietf.org/doc/html/rfc5737))

**Comment by fffonion** [comment]
looks like there does exist some test in spec/01-unit/21-dns-client/02-client_spec.lua are doing real DNS queries,
i will fix them to honor system resolv.conf next week.

**Comment by fffonion** [comment]
@hanshuebner can use another review now, thanks!

**Review by hanshuebner — APPROVED** [review]

**Pull request merged**
