### PR TITLE
chore(ci): migrate some CI from Jenkins to github actions

### PR DESCRIPTION
**Pull request by hutchic**
This should purely be a lift and move with no new added functionality.

- On PR's do a single test build
- On commits to release branches do all unofficial builds (excluding arm64)

### CODE REVIEW

**Comment by hutchic** [comment]
super-ceded by https://github.com/Kong/kong/pull/9807

**Comment by hutchic** [comment]
closed the wrong PR

**Review by mayocream — APPROVED** [review]

**Comment by mashapedeployment** [comment]
The backport to `release/2.8.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/2.8.x release/2.8.x
# Navigate to the new working tree
cd .worktrees/backport-release/2.8.x
# Create a new branch
git switch --create backport-9795-to-release/2.8.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick -x --mainline 1 b1a1f07fe9ebc58bd4d202345e733c945c50b398
# Push it to GitHub
git push --set-upstream origin backport-9795-to-release/2.8.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/2.8.x
```
Then, create a pull request where the `base` branch is `release/2.8.x` and the `compare`/`head` branch is `backport-9795-to-release/2.8.x`.

**Comment by mashapedeployment** [comment]
The backport to `release/3.0.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.0.x release/3.0.x
# Navigate to the new working tree
cd .worktrees/backport-release/3.0.x
# Create a new branch
git switch --create backport-9795-to-release/3.0.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick -x --mainline 1 b1a1f07fe9ebc58bd4d202345e733c945c50b398
# Push it to GitHub
git push --set-upstream origin backport-9795-to-release/3.0.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.0.x
```
Then, create a pull request where the `base` branch is `release/3.0.x` and the `compare`/`head` branch is `backport-9795-to-release/3.0.x`.

**Pull request merged**
