### PR TITLE
chore(build): tag Postgres version to 9.5 to respect the kong.conf.fault

### PR DESCRIPTION
**Pull request by vm-001**
https://github.com/Kong/kong/blob/3ee58cb7587c956ecb326abdcfd1666859e9708d/kong.conf.default#L1156

### CODE REVIEW

**Comment by bungle** [comment]
@kikito, @hbagdi, a bit unrelated comment, but I think we should be following a bit closer the Postgres policies:
https://www.postgresql.org/support/versioning/

Which means we should bump lowest Postgres to 11.20.

@vm-001,

When it comes to testing, we have traditionally used just latest available Postgres. I think at some point we debated this a bit. Major releases can break either way, so pinning to Postgres 9.5 may not be any better than pinning to latest. Theoretically at least we should test against first supported PG and last supported PG.

**Comment by hbagdi** [comment]
1. We most certainly need to bump the minimum supported version for Postgres up. 9.5 isn't even supported.
2. Running tests on the latest Postgres is okay for now. We will need to run tests against multiple Postgres versions soon but not doing that is ok.
3. Running tests on 9.5 makes little sense and we shouldn't do that since no production use-case should be using 9.5 anyway. If someone does that, it is their problem, not ours.
4. We have been relying on the fantastic track record of Postgres and the absence of non-breaking changes in their recent releases (so far as Kong's use of Postgres is concerned) and we have not found any issues.

Leaving this is as is for the best. We will revisit this later.

**Comment by vm-001** [comment]
> @kikito, @hbagdi, a bit unrelated comment, but I think we should be following a bit closer the Postgres policies: https://www.postgresql.org/support/versioning/
> 
> Which means we should bump lowest Postgres to 11.20 (as of writing this comment). Our migrations would benefit from the added `IF EXISTS` statements (now supported more broadly than in 9.5).
> 
> @vm-001,
> 
> When it comes to testing, we have traditionally used just latest available Postgres. I think at some point we debated this a bit. Major releases can break either way, so pinning to Postgres 9.5 may not be any better than pinning to latest. Theoretically at least we should test against first supported PG and last supported PG.

No matter which oldest version Kong can support, I recommend Kong uses that version in any place for consistency(except the PG latest version test). By the way, I made this PR because my GUI tool break because it does not support the latest PG version.

**Comment by hbagdi** [comment]
We cannot run tests on an outdated and no longer supported version of Postgres. Could you please use a different tool for your purpose?

**Comment by hbagdi** [comment]
We have no plans to pin. We try to use the latest version of our dependencies where possible.

**Pull request closed without merging**
