### PR TITLE
feat(*): bump OpenSSL to 3.0.8

### PR DESCRIPTION
**Pull request by fffonion**
Reason for the bump:
- Version 1.1.1 will be supported until 2023-09-11 (LTS). https://www.openssl.org/policies/releasestrat.html
- OpenSSL 3.0.0 FIPS module has got its certificate. https://www.openssl.org/blog/blog/2022/08/24/FIPS-validation-certificate-issued/
- lua-resty-openssl has been running CI with openresty with openssl 3.x since release and haven't seen major issues.

Note for reviewers: since OpenSSL 3.0 is a LTS release, we will first bump to 3.0.8, backport the change, and then bump to OpenSSL 3.1 on master.

KAG-1674

### CODE REVIEW

**Comment by fffonion** [comment]
TODO: update manifest

**Comment by chronolaw** [comment]
We need a change log entry for it.

**Comment by hbagdi** [comment]
We have temporarily put a pause on this one. We will be re-opening it in the future. (talked to Wangchong out of band)

**Comment by fffonion** [comment]
good run for packaging https://github.com/Kong/kong/actions/runs/5118902690/jobs/9203531413?pr=10180

**Review by windmgc — APPROVED** [review]

**Pull request merged**
