### PR TITLE
style(core/init): wrap `worker_id() == 0` as `is_busy_worker`

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

wrap `worker_id() == 0` as function `is_busy_worker`, perhaps we should give it a better name.

### CODE REVIEW

**Comment by dndx** [comment]
I don't feel this optimization is very necessary. `worker_id() == 0 ` is already very easy to understand.

**Comment by chronolaw** [comment]
> I don't feel this optimization is very necessary. `worker_id() == 0 ` is already very easy to understand.

It gives us more possibilities, we may change the worker process, such as the last worker or privileged worker.

**Comment by dndx** [comment]
@chronolaw Seems to be a very remote possibility IMO.

**Comment by chronolaw** [comment]
As the discussion above, we don't need this PR now.

**Pull request closed without merging**
