### PR TITLE
chore(dev): prioritize .lua over .ljbc in LUA_PATH

### PR DESCRIPTION
**Pull request by outsinre**
### Summary

chore(dev): prioritize `.lua` over `.ljbc` in `LUA_PATH`

We may edit Lua files in place for debug.

### Checklist

- [n/a] The Pull Request has tests
- [n/a] There's an entry in the CHANGELOG
- [n/a] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* Place `.lua` in front of `.ljbc` in `LUA_PATH`.
* Support custom pluin `KONG_PLUGIN_PATH`.

### Issue reference

Fix #_[FTI-5013]_

[FTI-5013]: https://konghq.atlassian.net/browse/FTI-5013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by fffonion — APPROVED** [review]

**Comment by fffonion** [comment]
merge on ci green. @outsinre please also backport this to EE

**Comment by fffonion** [comment]
@outsinre let's not go with the KONG_PLUGIN_PATH approach, instead, just prepend every directory in of plugins-ee onto LUA_PATH.

**Comment by outsinre** [comment]
> @outsinre let's not go with the KONG_PLUGIN_PATH approach, instead, just prepend every directory in of plugins-ee onto LUA_PATH.

Yep. Let me do a full test locally and update later on.

**Review by hanshuebner — APPROVED** [review]

**Comment by outsinre** [comment]
I tried to add all EE plugins to `LUA_PATH` but failed due to the limit of Nginx. See https://trac.nginx.org/nginx/ticket/1988

```
./?.lua;./?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/xml-threat-protection/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/xml-threat-protection/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/websocket-validator/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/websocket-validator/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/websocket-size-limit/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/websocket-size-limit/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/vault-auth/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/vault-auth/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/upstream-timeout/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/upstream-timeout/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/tls-metadata-headers/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/tls-metadata-headers/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/tls-handshake-modifier/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/tls-handshake-modifier/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/statsd-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/statsd-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/saml/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/saml/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/route-transformer-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/route-transformer-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/route-by-header/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/route-by-header/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/response-transformer-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/response-transformer-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/request-validator/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/request-validator/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/request-transformer-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/request-transformer-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/rate-limiting-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/rate-limiting-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/proxy-cache-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/proxy-cache-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/openid-connect/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/openid-connect/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/opa/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/opa/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/oauth2-introspection/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/oauth2-introspection/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/oas-validation/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/oas-validation/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/mtls-auth/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/mtls-auth/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/mocking/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/mocking/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/ldap-auth-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/ldap-auth-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/konnect-application-auth/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/konnect-application-auth/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/key-auth-enc/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/key-auth-enc/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/kafka-upstream/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/kafka-upstream/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/kafka-log/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/kafka-log/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/jwt-signer/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/jwt-signer/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/jwe-decrypt/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/jwe-decrypt/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/jq/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/jq/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/graphql-rate-limiting-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/graphql-rate-limiting-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/graphql-proxy-cache-advanced/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/graphql-proxy-cache-advanced/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/forward-proxy/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/forward-proxy/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/exit-transformer/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/exit-transformer/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/degraphql/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/degraphql/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/datadog-tracing/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/datadog-tracing/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/canary/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/canary/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/application-registration/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/application-registration/?/init.lua;/Users/zachary/workspace/kong-ee/plugins-ee/app-dynamics/?.lua;/Users/zachary/workspace/kong-ee/plugins-ee/app-dynamics/?/init.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/share/lua/5.1/?.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/share/lua/5.1/?.ljbc;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/share/lua/5.1/?/init.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/share/lua/5.1/?/init.ljbc;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/site/lualib/?.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/site/lualib/?.ljbc;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/site/lualib/?/init.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/site/lualib/?/init.ljbc;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/lualib/?.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/lualib/?.ljbc;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/lualib/?/init.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/lualib/?/init.ljbc;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/Users/zachary/workspace/kong-ee/bazel-bin/build/kong-dev/openresty/luajit/share/luajit-2.1.0-beta3/?.ljbc;;
```

**Comment by outsinre** [comment]
The `KONG_PLUGIN_PATH` I added is to add the ability to mount custom plugins to the bazel venv.

So, we can debug plugins that are written by customers or personal plugins against Kong.

**Comment by outsinre** [comment]
Cherry-pick: https://github.com/Kong/kong-ee/pull/5082

**Pull request merged**
