### PR TITLE
Rebuild the router through events rather than at the access phase 

### PR DESCRIPTION
**Pull request by ganeshs**
NOTE: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributing

### Summary
Made a fix to not rebuild the router during the access phase. The approach I have tried is to trigger a worker_events.post to rebuild on all workers in the local node when there's a change in route. And also subscribe to cluster_events invalidations on 'router:version' to rebuild the router

### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issues resolved

Fix https://github.com/Kong/kong/issues/3634

### CODE REVIEW

**Comment by ganeshs** [comment]
@thibaultcha Thanks for your response. Our throughput is pretty high ~50000 rps going through 10+ kong nodes. Addition/Removal of routes happen once or twice a day and the current implementation blocks the incoming requests as the db connections go for a toss. This results in resp times increasing for the callers upto a minute in the worst case. 

 I didn't clearly understand the concerns related to eventual consistency. Are you referring to the event getting lost in some of the workers? I can see this happen when there's an error in processing the callback. I agree this need to be handled. 

> Overall, the proper "fix" here would probably be to allow for the router to receive atomic updates, e.g. being more granular when adding Routes/Services, and not require a complete rebuild for every CRUD operation exercised on these entities. That is an optimization on our TODO list, but we have yet to take care of it yet.
We are kind of blocked on this change. Have applied this patch to our production servers and its been running smooth for the past 2 weeks without any issues. While I understand the patch is far from a proper fix, do you have any suggestions how we can live with this till we have proper fix. Thanks

**Comment by thibaultcha** [comment]
> I didn't clearly understand the concerns related to eventual consistency. Are you referring to the event getting lost in some of the workers?

I am referring to the time it takes for the even to propagate amongst the workers.

> We are kind of blocked on this change. Have applied this patch to our production servers and its been running smooth for the past 2 weeks without any issues.

While this patch may fix your use-case (which is great! yay open source!), it isn't something we can consider on our side given the concerns cited above. There are other ways to reduce the impact made to the DB when applying Services/Routes changes but they are all non-trivial to develop and test.

**Comment by ganeshs** [comment]
> I am referring to the time it takes for the even to propagate amongst the workers.

Sorry my understanding of kong internals is limited. But can't this be controlled by setting polling frequency to 1s? Or are we talking about workers not being consistent during that 1s interval?

While we can live with the patch for interim, is there any timeline that I can wait for an official fix to be released. I would be glad to help out with the fix if we know of an approach.

**Comment by thibaultcha** [comment]
> Or are we talking about workers not being consistent during that 1s interval?

Indeed. Which, as I've said, has been an issue in the past for a number of confused users and caused us a recurring flow of support requests and GitHub issues.

> While we can live with the patch for interim, is there any timeline that I can wait for an official fix to be released.

We're not focusing our efforts on the router at this point, but a few possibilities to consider:

- Use lua-resty-worker-events `poll()` function as previously suggested
- Cache Routes/Services into a shared memory zone (lua_shared_dict/kong.cache) to limit the number of database queries on a rebuild
- Improve the router to accept granular updates of Routes/Services

All of these solutions come with their own pros and cons, and you are welcome to try any of these, but the results would ideally require careful testing and benchmarking (i.e. does the cost of calling `poll()` - which is _usually_ cheap - on the proxy code path is actually worth it, will this even make a difference on a busy node, that is, in 1s, there is little chance that no workers would not process any requests and thus trigger a rebuild from the access phase anyway, how would a shared memory zone cache implementation behave when all of the Services/Routes do not fit in it, etc...).

I will leave this open for discussion for some more time if anyone else wants to jump in, but labelling it as such!

**Comment by thibaultcha** [comment]
Closing this, as I feel like the discussion has reached a stall point, and there has been no development in the last 2 weeks. Hopefully this PR stays visible, along with this thread!

**Pull request closed without merging**
