### PR TITLE
feat(pdk) kong request cookie

### PR DESCRIPTION
**Pull request by fairyqb**
Summary

add kong.request.cookie(name) and cookies()

### CODE REVIEW

**Review by Tieske — COMMENTED** [review]
lgtm, @bungle mind having a look as well?

**Comment by fairyqb** [comment]
@gszr  request review and merge.

**Comment by fairyqb** [comment]
@kikito

**Comment by bungle** [comment]
Only thing I don't like about this is the usage of `resty.cookie`. I was just thinking about getting rid of that dependency. Reading cookies is really simple as you can just: `ngx.var.cookie_<mycookie>`.

**Comment by hishamhm** [comment]
@bungle would the implementation of `get_cookies` (to get all) be equally simple?

If so, @fairyqb, would you like to give it a try using `ngx.var` directly?

**Comment by bungle** [comment]
> @bungle would the implementation of `get_cookies` (to get all) be equally simple?

It is not that simple for sure, but it is not difficult either. The resty.cookie is not well-maintained and rock is not updated. It has other issues too, and then it inserts its own semantics.

**Comment by fairyqb** [comment]
Some checks were not successful ???
Build & Test / Lint & Unit (pull_request) Failing after 3m — Lint & Unit

**Comment by fairyqb** [comment]
Some checks were not successful   ??
Build & Test / Lint & Unit (pull_request)

**Comment by fairyqb** [comment]
Some checks were not successful ??
Build & Test / Lint & Unit (pull_request)
Error: /28 06:13:46 [error] 205#0: *2 [lua] balancer.lua:1145: execute(): DNS resolution failed: dns server error: 3 name error

WHY ???
@bungle  @hishamhm @Tieske

**Comment by kikito** [comment]
@fairyqb that balancer/dns error is a flaky test, unrelated to your PR. We have had it for a while. It usually "recovers" with 1 or 2 retries. I have noticed that travis was red as well (for seemingly unrelated reasons, on http_log) so I have restarted the tests.

If the tests keep failing, please try rebasing over `next`. We recently included fixes related with the way CI uses the cache which might resolve this problem.

**Comment by fairyqb** [comment]
move new PR: #6534

**Pull request closed without merging**
