### PR TITLE
feat(hybrid): report configuration of DP to the CP

### PR DESCRIPTION
**Pull request by hbagdi**
### Summary

With this patch, kong.conf settings of a DP are self-reported to the CP. Sensitive credentials from kong.conf are redacted before they are sent to the CP.
This patch reports the configuration, LuaCP isn't going to do anything with it just yet. This feature is specific to Kong Inc's Konnect offering.

### Checklist

- [x] The Pull Request has tests
- [x] There's an entry in the CHANGELOG - None because the patch has no end-user visible changes (yet)
- [x] There is a user-facing docs PR - None because the patch has no end-user visible changes (yet)

### CODE REVIEW

**Comment by hbagdi** [comment]
@samugi Putting a hold until we get a +1 from team-koko.

**Comment by samugi** [comment]
I committed a small change to the tests, lgtm

**Review by samugi — APPROVED** [review]

**Review by GGabriele — APPROVED** [review]
Thanks a lot!

**Comment by jschmid1** [comment]
> @samugi Putting a hold until we get a +1 from team-koko.


@GGabriele approved. Merging

**Pull request merged**
