### PR TITLE
feat(termination) add avert + trigger/avert _value conf

### PR DESCRIPTION
**Pull request by jeremyjpj0916**
### Summary

This PR adds two concepts:
1. Allowing the value to be specified per header/query param for more specific use cases.
2. The avert which acts as a polar opposite to trigger. Dictating when to prevent the plugin execution.

Relevant Docs PR:
https://github.com/Kong/docs.konghq.com/pull/3965

### CODE REVIEW

**Comment by jeremyjpj0916** [comment]
Hmm seems failures are not even based on my plugin enhancements? Odd considering this is the master branch which I would expect stable.

**Review by Tieske — CHANGES_REQUESTED** [review]
lgtm. Just not sure about the name; avert, or maybe skip_trigger? (not a native speaker)

would you mind rebasing the PR @jeremyjpj0916 ?

**Comment by hbagdi** [comment]
Please use header-based routing for this purpose.

**Comment by jeremyjpj0916** [comment]
I don't think header based routing solves what this PR solves. This PR is all about being able to allow traffic you want and reject traffic you don't based on a seen header.

**Comment by hbagdi** [comment]
> This PR is all about being able to allow traffic you want and reject traffic you don't based on a seen header.

Can you elaborate a bit more on why header-based route matching (and then enabling a plugin on that route) doesn't work for your use-case?

**Pull request closed without merging**
