### PR TITLE
chore(conf): add .editorconfig

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Add .editorconfig

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
There are a few files that use four spaces for indentation, such as the nginx templates and fixtures template. Shall we take these into consideration as well?

**Comment by bungle** [comment]
@p0pr0ck5 I know, and a lot of maybe old code that was using different indentation (4 spaces is most common, I think). All the discussion is welcomed. I don't have preference in any direction at this point. I merely did this to pass on some silent information.

**Comment by p0pr0ck5** [comment]
Yeah, I'm in favor of this, I'm unsure of how these files will interact with such a config. Is it possible to add entries for these files with the correct `indent_size` value?

**Comment by bungle** [comment]
@p0pr0ck5, certainly we can add different configs for the files that currently have different indentation. However, not sure if it worth it if they will later on follow the same formatting. What do others think?

**Comment by hishamhm** [comment]
I was just about to propose a PR adding an equivalent `.editorconfig` file. Text editors do not reformat a file when they open it, so even if the configuration doesn't match, nothing will break caused by this. Here is my proposed revised `.editorconfig` file:

```

root                     = true

[*]
end_of_line              = lf
insert_final_newline     = true
trim_trailing_whitespace = true
charset                  = utf-8

[*.lua]
indent_style             = space
indent_size              = 2

[kong/template/nginx*]
indent_style             = space
indent_size              = 2

[*.template]
indent_style             = space
indent_size              = 4

[Makefile]
indent_style = tab
```

**Comment by hishamhm** [comment]
Force-pushed an updated version of the file as per @bungle's request.

**Comment by bungle** [comment]
LGTM, but I cannot approve this as I created it.

**Pull request merged**
