### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
added LICENSE badge

NOTE: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributing

### Summary

Added License badge

### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issues resolved

Fix #XXX

### CODE REVIEW

**Comment by thibaultcha** [comment]
See #3920.

**Comment by vyaspranjal33** [comment]
@thibaultcha  whats wrong with adding LICENSE badge ?

**Comment by thibaultcha** [comment]
You're right, a license badge is a nice to have. I misread the patch, thanks for pointing it out. It has been merged to master.

Please note that such minor contributions are not considered valid for Hacktoberfest or receiving a Kong contributor T-shirt though.

**Comment by vyaspranjal33** [comment]
@thibaultcha  No clarification for such thing  have been given in CONTRIBUTING /Tshirt section

**Pull request closed without merging**
