### PR TITLE
chore(conf) worker_rlimit_nofile & worker_connections "auto" == max 16384

### PR DESCRIPTION
**Pull request by bungle**
### Summary

- Adds a test for `nginx_main_worker_rlimit_nofile=auto` and
  `nginx_events_worker_connections=auto`
- Adds documentation for `nginx_main_worker_rlimit_nofile=auto` and
  `nginx_events_worker_connections=auto`
- Renames some variables to avoid further confusion

### CODE REVIEW

**Comment by hishamhm** [comment]
What is the memory impact of this change for users running the default settings?

**Comment by bungle** [comment]
> What is the memory impact of this change for users running the default settings?

On my machine 16k is about 44k worker process, and 64k is about 66k worker process.

**Comment by hbagdi** [comment]
Based on internal discussions, didn't we all agree that this is not an issue?

**Comment by bungle** [comment]
@hbagdi, yes we did, but this pr contains good tests etc. that we still want in.

**Pull request merged**
