### PR TITLE
release: 3.3.2

### PR DESCRIPTION
**Pull request by kikito**
Bumping version number to 3.3.2 as part of the post-release steps for 3.3.1

### Summary

This is a simple bump to the meta info on the 3.3 branch. It was stuck unmerged for months because the upgrade tests where failing. I have taken the executive decision of neutering the upgrade tests in the 3.3 branch. It is extremely unlikely that someone will want to upgrade to 3.3 in particular, given that 3.4 is LTS.

### Checklist

- [ ] The Pull Request has tests - not needed
- [ ] There's an entry in the CHANGELOG - not needed
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE - not needed

### Full changelog

* Bump version number to 3.3.2
* Deactivate upgrade tests

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Comment by kikito** [comment]
@outsinre could you approve this?

**Review by outsinre — APPROVED** [review]

**Comment by outsinre** [comment]
LGTM.

**Comment by AndyZhang0707** [comment]
@kikito could you follow up on this PR? Thx

**Review by hanshuebner — APPROVED** [review]

**Comment by dndx** [comment]
@kikito can we close this?

**Comment by jschmid1** [comment]
@kikito is this still valid?

**Comment by kikito** [comment]
@fffonion I am seeing a lua-resty-zlib related error on this PR. Could this be related with the changes you made to the library?

**Pull request merged**
