### PR TITLE
Added a checklist PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by sidhyatikku**
# Summary

Hey guy I have added a checklist to make contributors more aware of `CLA` and `Contributing guidelines`. With this checklist, Kong contributors can review all the necessary requirements and reviewer can see whether the checklist is complete, prioritise which PRs to review first (as the number of checklist items appears next to PR on the PR page), and can double check the CLA.

 # Preview

---------------------------------------------------------
## Checklist:

- [x] I have signed the [Kong Open Source CLA](https://cla-assistant.io/Kong/kong).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the guidelines in **CONTRIBUTING.MD** document.
- [x] All new and existing tests passed.
 ---------------------------------------------------------

### CODE REVIEW

**Comment by sidhyatikku** [comment]
I haven't edited any code or any file other than `PULL_REQUEST_TEMPLATE.MD` and I'm not sure why the Travis CI build failed.

**Comment by sidhyatikku** [comment]
Hey guys, I have just edited the `PULL_REQUEST_TEMPLATE.MD` file and I'm not sure why the Travis CI build is failing. This change affects GitHub and does not affect the codebase.

**Comment by thibaultcha** [comment]
Hi,

This checklist includes items that are redundant with the usual PR flow: CI results and CLA signing are already automated as part of the PR's UI, and the CONTRIBUTING.md file is already mentioned in the PR template. Thank you, but this checklist does not seem necessary, unless _maybe_ if revised to be more relevant to this project's contribution workflow.

**Comment by sidhyatikku** [comment]
Hi @thibaultcha,

If there any revisions, then please let me know.

**Comment by thibaultcha** [comment]
Closing this due to lack of activity/interest for the time being.

**Pull request closed without merging**
