### PR TITLE
fix(dao) cache invalidation on deletion of non-workspaceable daos

### PR DESCRIPTION
**Pull request by onematchfox**
### Summary

At present when a DAO is deleted, the cache key generated is always suffixed with the workspace id (see logs below for an example). This means that, for example, any custom plugin entities that are deleted via an admin API endpoint are not being evicted from the cache. This PR attempts to address the issue by ensuring that the `delete` and `delete_by_` DAO methods respect whether or not the entity schema is marked as `workspaceable`

```
2022/06/18 08:30:41 [debug] 8924#0: *25 [lua] events.lua:211: do_event(): worker-events: handling event; source=dao:crud, event=delete, pid=nil, data=table: 0x7f7f6033ae80
2022/06/18 08:30:41 [debug] 8924#0: *25 [lua] init.lua:229: invalidate_local(): [DB cache] invalidating (local): 'foreign_references:foreign-reference:::::aa1c7921-afad-4e48-bb9b-7234e7f37b5e'
2022/06/18 08:30:41 [debug] 8924#0: *25 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_db_cache, pid=8924, data=foreign_references:foreign-reference:::::aa1c7921-afad-4e48-bb9b-7234e7f37b5e
2022/06/18 08:30:41 [debug] 8924#0: *25 [lua] init.lua:250: invalidate(): [DB cache] broadcasting (cluster) invalidation for key: 'foreign_references:foreign-reference:::::aa1c7921-afad-4e48-bb9b-7234e7f37b5e'
```

### Full changelog

* Only set `show_ws_id` in delete methods to `true` if entity schema has `workspaceable == true`
* Added tests that ensure that non-workspaceable entities deleted via the admin API are correctly evicted from the cache
  - Note: I struggled to find the correct place to try and test this functionality. So, whilst the tests I have written do prove the point, I won't be surprised if there's a better way/place to do this. Feel free to point me in the right direction :smile:

### CODE REVIEW

**Comment by hbagdi** [comment]
ping @bungle for a review

**Comment by hbagdi** [comment]
Not at this point. We are running a tool to better track our work that assigns the author as the assignee.

**Comment by onematchfox** [comment]
@mheap as per our conversation at the booth this week, I'd really appreciate any assistance on getting this prioritized internally.

**Comment by onematchfox** [comment]
Hi @bungle, Thanks for taking a look at this!

I'm not sure I follow your suggestion (or at least the code you proposed). The issue could probably be approached by adjusting the `cache_key` function. It's been a while since I was in this code, but if memory serves me correctly, I think this would need to always append the workspace id, whereas the code you proposed explicitly sets it to `nil`. I also think this is likely to be a more _invasive_ change as you would also need to handle other areas in the codebase that currently cater for `show_ws_id`.

> In general it feels non-workspaceable entities should never care about this parameter or something. 

Yes, agreed, this should be the case.

> Need to dive a bit deeper what we mean about it. Why we have it in a first place (perhaps to hide workspaces on community edition to not display them as it only supports default workspace).

:+1:

**Comment by hbagdi** [comment]
Closing because of lack of activity. We would like to accept this contribution if anyone wishes to pick this back up.

**Comment by onematchfox** [comment]
@hbagdi, I'm a bit confused by your closing comment. I would be happy to adjust the code if required. But so far nothing has been requested of me. I was under the impression that this was in @bungle's hands so from my point of view the "lack of activity" is on Kong's side.

**Comment by onematchfox** [comment]
CC @mheap...

This isn't exactly the best contributor experience and is highly indicative of the experience I described when we met. 

The PR is a year old and solves a clear issue for (advanced) OS users - who have been _neglected_ at the expense of the commercial offering. I feel that I have been reactive to any comments from the maintainers and have even actively followed up through personal connections at conferences. Yet here I am being told that this is not enough... I haven't been active enough? What would the expected behaviour be here? Is the responsibility on me to @ maintainers weekly to ensure this issue was still active?

FWIW, I've moved on from Kong so best of luck to you all going forward. However, were I still invested in this ecosystem this would be a giant warning bell for me. How many other issues have been swept under the rug by similar actions?

**Comment by gszr** [comment]
Hi @onematchfox,

First of all, we apologize for closing this issue before an answer from us. We value the time and effort you put into reporting this issue and coming up with a fix.

I spent some time verifying this, and the issue no longer exists in latest Kong master. In order to demonstrate it, I created this PR adding one of your test cases to our code base: https://github.com/Kong/kong/pull/11201. I understand you may not be interested in pursuing this further, but would appreciate if you could take a look (no worries if not!)

Best wishes,
Guilherme

**Pull request closed without merging**
