### PR TITLE
tests(db): re-enable and fix flaky tests in spec/02-integration/03-db/07-tags_spec.lua

### PR DESCRIPTION
**Pull request by ADD-SP**
## Sumarry

Re-enabling and fixing some flaky tests disabled before.

[KAG-1318]

[KAG-1318]: https://konghq.atlassian.net/browse/KAG-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ADD-SP** [comment]
To backport manually, run these commands in your terminal
```shell
echo "testing
```

**Comment by hbagdi** [comment]
@ADD-SP Good to merge this?

**Comment by ADD-SP** [comment]
> @ADD-SP Good to merge this?

@hbagdi I have no access.

**Comment by hbagdi** [comment]
@bungle Could you please merge this one?

**Review by hanshuebner — APPROVED** [review]

**Pull request merged**
