### PR TITLE
chore(router) router expression name

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

`expressions` make a little confused, we rename it to `expression`. or `expressional `?

We should have more discussion of it.

### CODE REVIEW

**Review by bungle — APPROVED** [review]

**Comment by bungle** [comment]
`router_flavor`:´traditional´ /  `traditional_compatible`:
use: route.paths, route.headers, route.hosts, etc.

`router_flavor`: `expression`:
use: route.expression

The `route.paths` etc. are quite self-explanatory but `route.expression` feels like `where is the manual`. Ok, there is manual and we figure out you can use a new language, basically a DSL.

When debugging routing issues, we might ask `what router are you using?`. When the answer is `I am using router expression`, it feels strange. Don't all the routers have all sorts of expressions (isn't route.paths used inside somekind of expression inside router)? Or did you mean Router named Expression? A different flavor?

In entity the `route.expression` or `route.match_dsl` or `route.match` or `route.dsl` or `route.rules` or `route.match_rules` could be possible names. But `router_flavor` is different beast. How to call these different routers? Expression Based Router sounds better than Router Expression. DSL Router / Traditional Router and then we have Traditional Compatible Router too, which means `DSL Router that is initialized from Traditional Route Fields, like route.paths`. This is all really confusing.

**Comment by chronolaw** [comment]
The type of `route.expression` is `string`, not `array`, so it is ok.

**Comment by mheap** [comment]
@bungle Datong and I discussed calling the new router `dsl` and Datong felt like it was not accessible for a wider audience.

`expression` is the in-code name. In text, we'll always talk about `router expression` or `router expressions` depending on context

**Comment by bungle** [comment]
@mheap I have approved this, do you think we should merge it? @chronolaw, @dndx?

**Comment by dndx** [comment]
@bungle Under debate, do NOT merge it yet.

**Comment by dndx** [comment]
Discussed with @mheap , this PR is closed because it follows existing conventions in other Kong features. e.g. Routes vs Route. Certificates vs certificate.

**Pull request closed without merging**
