### PR TITLE
Merge master into next 2019-12-12

### PR DESCRIPTION
**Pull request by hishamhm**
Please approve once CI passes, but DO NOT MERGE.

### CODE REVIEW

**Comment by hishamhm** [comment]
@zeeshen @suijaa our CLA assistant was recently reset, could you re-sign? Thank you!

**Comment by suijaa** [comment]
done

Thanks & Regards
Nishith Gadhiya

**Comment by hishamhm** [comment]
thank you @suijaa !

**Comment by suijaa** [comment]
Hello Hisham,

I have filled the contributor's form. Can you please tell me that I am
eligible to get the cool Kong Tshirt?

Thankyou

**Pull request merged**
