### PR TITLE
[backport 3.4]feat(router/atc): http segments matching and other improvements

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

KAG-3586

In 3.4 we have no `request_aware_table`, so I replace it with `tb_new/tb_clear`.

git cherry-pick 2457ef05e165d5db5cab077fc4a5b4c58196219f  #11388
git cherry-pick 36647f2aab00441146c32b16c092ef2a46fd4728  #11430
git cherry-pick 8cd18bcde1c4d429d844cf43c9b5bab20f8bc73c  #11411
git cherry-pick ba559eadf3468b77260413831405e17f3c326206  #11449

git cherry-pick 59670a105cc7363333ad3bc2914d43c38e4ced98  #11721
git cherry-pick 5f5e272a684c9952fe57456de471b041f105c712  #11904
git cherry-pick 6ce12628e05f4aa3e5c90ab518729fa8825191d2  #11905
git cherry-pick 37bd9c2f94267538ecf518bc5ca8545302594290  #11914
git cherry-pick 12f45ad91b7ab696172ca2244bc96fec8304613d  #11948
git cherry-pick c9fd6c127a9576da09d9af4fa4ba1139b30b3509  #12127
git cherry-pick 8c2b5a4e7a35da88bbbd5b78507b8a292597d420  #12258
git cherry-pick 86f0a6cfcbd477c0a51243c330bdd47a2abff2fc  #12261, fixing *.test
git cherry-pick f49abd69c70eb719b53b84db21a1756743c089a6  #12180, fixing *.test https://github.com/Kong/kong/pull/12268/files#diff-50dcfdce82665f85d2027363af6956fc788e5b8f6c6b8de907e9bd82e8871501
git cherry-pick 11d7639bb71326eff5bbcdf73b0e35f03d4763df  #12266
git cherry-pick 560fdfb599da87666e3d5e86d1b7ac59eb64e479  #11950
git cherry-pick ce12f68d0c286564df39fc28b43ec97a64749219  #12307, fixing *.test
git cherry-pick 9305665e89f8c83b24c9c3943e83ffaa46b7cb2e  #12283
git cherry-pick ef87932b612f4a0961f011290e344b7aa46fb944  #12378

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Review by nowNick — APPROVED** [review]
Looks good to me!

I have some questions that I was curious about:

1. Could you expand a little bit on the request-aware-table smaller fix? How does it impact / change the behaviour when you use `tb_new/tb_clear` compared to with / without request-aware-table? As far as I remember request-aware-table was only a test utility to detect if a corruption is happening. On _normal_ flow it is not triggered  - am I correct? 🤔 

2. Does it make sense to cherry pick: https://github.com/Kong/kong/pull/12400/commits/57df3bc2277ae9e2fbf49fd5bf39bea9f4907fe4 if later on you revert those changes with: https://github.com/Kong/kong/pull/12400/commits/4aad7d2376ce65839b9786df4a25702c6301aa6e ?

3. Note: _Super-tiny / nitpick:_
In the PR description you point to: `git cherry-pick f49abd69c70eb719b53b84db21a1756743c089a6 https://github.com/Kong/kong/pull/12180, fixing *.test` which might sound like we want to backport test scheduler. I wonder if it would be more helpful to point to this: https://github.com/Kong/kong/pull/12268/files#diff-50dcfdce82665f85d2027363af6956fc788e5b8f6c6b8de907e9bd82e8871501
But it's just a PR description fix if anybody would like to dig it up in future.

**Comment by chobits** [comment]
focusing on this commits which are different between the master as chrono said in description

image

And some PRs have been also intergrated into `release/3.4.x`, but you do not mention them in your description.

**Review by chobits — APPROVED** [review]

**Comment by chronolaw** [comment]
The reviewers can refer to ticket KAG-3586, which recorded all the picked PRs.

**Comment by chobits** [comment]
TODO: I'll assist with running perf test after this PR is merged.

**Comment by chobits** [comment]
running perf test for this PR's image `kong/kong:90a783b8388db4e1cc290c34c9d5617a6cacc841-ubuntu` ([here](https://github.com/Kong/kong/actions/runs/8135072729/job/22229082667?pr=12400)) compared to `3.4.3.4`

**Review by ADD-SP — APPROVED** [review]

**Pull request merged**
