### PR TITLE
Release: 2.0.0rc1

### PR DESCRIPTION
**Pull request by hishamhm**

### CODE REVIEW

**Comment by hishamhm** [comment]
Hello @mvanholsteijn @artomal @StrikerRUS @davinwang @james-callahan — our CLA signatures were recently refreshed and unfortunately this means that commits that had their CLA already signed before now have the bot complain once we merge them to other branches. Could you go through the CLA Assistant and re-sign? Thank you and sorry for the inconvenience!

**Comment by StrikerRUS** [comment]
@hishamhm Done!

**Comment by james-callahan** [comment]
I never agreed to the CLA.

**Comment by hishamhm** [comment]
> I never agreed to the CLA.

@james-callahan This had been done implicitly for Kong employees before, but for some reason the CLA database was reset recently. Your commit in this branch was a cherry pick from an old PR from back when you were with the company, so I thought I'd carry on with the release, as the original PR had no CLA complaints. If you could go through the CLA assistant, that would prevent similar warnings on future merges of this branch — thank you!

**Comment by narate** [comment]
Kong Hybrid Mode is great!
I have tried it and loved it, but how to get Prometheus metrics for each data plane node ?

**Comment by dndx** [comment]
@narate https://github.com/Kong/kong/blob/next/kong.conf.default#L337-L347
https://docs.konghq.com/1.4.x/configuration/#status_listen

You can use the `status_listen` config to enable a special port on each DP for Prometheus to access.

Let me know if you need further help on this!

**Comment by narate** [comment]
@dndx Thank you. It works! 👍

**Pull request closed without merging**
