### PR TITLE
add extend points in nginx/kong conf templates

### PR DESCRIPTION
**Pull request by passos**
### Summary

Add three extendsion points in nginx configuration template so that user can put their extend configuration in their own directory instead of update the template file in system library.

### Full changelog

* kong/templates/nginx.lua
* kong/templates/nginx_kong.lua

### CODE REVIEW

**Comment by thibaultcha** [comment]
This is a good idea. However, wouldn't it be friendlier to include `kong_*.conf`? We do not have a `conf.d` directory in our Nginx prefix.

@passos FYI, did you get a look at #2355? I like to point this out to what we call "Nginx power users" (people coming to Kong who already knew about Nginx and its internals, and are looking at way to customize their Kong/Nginx instance). The idea is that we know Nginx customization currently is a pain, and we are trying to gather feedback on this idea to better understand if it would improve Kong, or break assumptions about its simplicity and Nginx abstraction.

**Comment by p0pr0ck5** [comment]
@passos any update?

**Comment by p0pr0ck5** [comment]
@passos ping

**Comment by passos** [comment]
@p0pr0ck5 yes, it's good to just include the file with `.conf` extension. I just updated and commited the change. However this is just a change in configuration template, I have tested it from my local machine but I am not sure how to write unit test for it.

**Comment by thibaultcha** [comment]
Closing due to lack of updates.

**Pull request closed without merging**
