### PR TITLE
chore(rate-limiting) bump plugin version

### PR DESCRIPTION
**Pull request by locao**
There's a new plugin schema field to support redis username, added in #8032, so we need to bump plugin's version.

### CODE REVIEW

**Review by bungle — APPROVED** [review]

**Review by dndx — APPROVED** [review]
Do we need to add the new field into https://github.com/Kong/kong/blob/master/kong/clustering/compat/removed_fields.lua?

**Comment by locao** [comment]
> Do we need to add the new field into https://github.com/Kong/kong/blob/master/kong/clustering/compat/removed_fields.lua?

It seems we should add it, yes. So I guess this bump will have to wait until next release, wdyt?

**Comment by bungle** [comment]
> > Do we need to add the new field into https://github.com/Kong/kong/blob/master/kong/clustering/compat/removed_fields.lua?
> 
> It seems we should add it, yes. So I guess this bump will have to wait until next release, wdyt?

The bump does not change the fact that change is already merged and included in `release/2.7.x`. The minor bump is fine according to this: https://github.com/Kong/kong/blob/master/kong/clustering/control_plane.lua#L469-L470

In my opinion I would just add another commit here that adds the `username` to removed fields, and include it in `2.7`. The other solution is worse where we actually now need to remove that other commit. But please find confirmation on what to do.

**Comment by locao** [comment]
not releasing this at this point.

**Pull request closed without merging**
