### PR TITLE
chore(ci): add s390x arch support

### PR DESCRIPTION
**Pull request by Repana-Chowdappa**
### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

### CODE REVIEW

**Comment by hanshuebner** [comment]
Thank you for this contribution!  Please address the failures found the in the check run.  We're going to provide additional feedback once we have reviewed.

**Comment by fffonion** [comment]
It feels easier to do with a cross-compile, then you don't need to wait for nfpm etc to release s390x artifacts. Just duplicate what exist for aarch64 to s390x would work.

**Comment by ADD-SP** [comment]
Internal discussion is ongoing, I converted this to a draft to avoid unintended merge.

**Comment by hanshuebner** [comment]
At this point, we do not have the hardware to verify that the changes actually work.  @Repana-Chowdappa Are you running this anywhere?  Do you have any idea how we could include the architecture into our CI testing?

**Comment by SriramaSharma** [comment]
> At this point, we do not have the hardware to verify that the changes actually work. @Repana-Chowdappa Are you running this anywhere? 

@hanshuebner , with the changes @Repana-Chowdappa has proposed, we have been able to build kong on s390x VM and we have been able to get it up and running. 


> Do you have any idea how we could include the architecture into our CI testing?

There is a process through which we can extend a s390x VM instance installed with Linux which can then be plugged into the community CI testing. I can share more details regarding this. Meanwhile, Could you please share info or point me to details of the community CI/CD and what would be the minimum requirement for a build node (presumably Linux) to include it into community CI/CD ?

**Comment by hanshuebner** [comment]
> Could you please share info or point me to details of the community CI/CD and what would be the minimum requirement for a build node (presumably Linux) to include it into community CI/CD ?

Our basic concern is that we don't have in-house knowledge or experience with s390x.  For the mainstream architectures, we're confident enough that the CI testing based on ubuntu-22.04 on amd64 for the open source version of Kong Gateway sufficiently covers testing requirements for ARM based systems as well.  In our enterprise offering, we're also running CI tests with arm64.

Given our lack of experience, we're not going to be able to provide s390x platform support for the community, but we may be able to include the platform as community supported.  For that, we'll need to have a separate README markdown file that describes the status of support and contains any additional information that'd be useful to people using that platform.  The document should also describe how the CI test suite can be run manually to verify that s390x support works.  The basic prerequisite for making that work is that GitHub Action runners based on the s390x platform will be needed.

We're open to discussing other approaches.  Basically, we don't have commercial interest in the port so the amount of resources that we can put into supporting it is limited.  At this point, we like the idea of having s390x support for its geek value.

**Comment by Repana-Chowdappa** [comment]
@hanshuebner - We are working on bazel team to get dependency Buildifier binary for s390x. Once this available this CI failures will get resolve. Then we will try to provide s390x Infra (VM) to get tested on platform.

**Comment by MaryJulian17** [comment]
Hi, is there any plan to get this integrated in the CI? This would be helpful for my team.

**Pull request closed without merging**
