### PR TITLE
refactor(router) move path construction to after_access

### PR DESCRIPTION
**Pull request by Tieske**
The router was responsible for path construction but this would
happen in the before-access phase. Allowing path manipulation to
only be done on the full path, not on the individual components.

This commit changes it by creating an intermediate table with the
path components (for plugins to modify) and does the final
construction only in the after-access phase

### CODE REVIEW

**Comment by hishamhm** [comment]
@Tieske could you take a look at the failing tests before we review?

**Comment by hishamhm** [comment]
@Tieske looks like the tests are still failing

**Comment by hishamhm** [comment]
@Tieske ping?

**Comment by Tieske** [comment]
leaving the branch around, just-in-case

**Comment by windmgc** [comment]
@Tieske Just out of curiosity, why this PR didn't get merged?

**Comment by Tieske** [comment]
because it never passed and got outdated (again), and hasn't gotten priority yet. It is still on the radar however

**Pull request closed without merging**
