### PR TITLE
Replace graph with timeseries, Kong3 Upgrade

### PR DESCRIPTION
**Pull request by marinflorin**
### Summary

Note: [Time series panel](https://grafana.com/docs/grafana/latest/visualizations/time-series/) visualization is going to replace the Graph panel visualization in a future release.
Fix queries for service to match the Kong service

### Full changelog

* Replace Dashboard graphs with time series
* Add unit for requests/second, latency, bandwidth, etc
* Update time series to match the old design
* Queries are using ``service`` instead of ``exported_service``, which translates to Kubernetes service, something like kong-kong-proxy instead of the actual service/api.

### Reference

- [Grafana docs for graph](https://grafana.com/docs/grafana/latest/visualizations/graph-panel/)

### CODE REVIEW

**Comment by hbagdi** [comment]
Can you please sign the CLA?
@fffonion Do you happen to have a Grafana instance to verify this one?

**Comment by fffonion** [comment]
@hbagdi I do have one locally, will test it against Kong.

**Comment by fffonion** [comment]
screencapture-localhost-3000-d-mY9p7dQmz-kong-official-2022-05-13-15_49_04
looks like working, one thing is that we shouldn't be doing the `exported_service` change on grafana side, as that will break for users that are not using k8s. you should do the relabeling in prometheus when scraping instead.

**Comment by marinflorin** [comment]
Hey, sorry for the late response, I just got back from a vacation.

I will take care of those this week, I will also add the Prometheus Re-labeling to the dashboard documentation.

Thank you!

**Comment by hbagdi** [comment]
@marinflorin Could you please rebase this one again? We dropped the ball on this one, I apologize.

**Comment by marinflorin** [comment]
Hey @hbagdi,

First of all, there is no need to apologize. I am a Kong Enthusiast, and contributing to Kong (even the smallest fix) is my pleasure.

I have rebased the changes and added a few fixes:
- upgrade metrics to correspond to Kong 3 changes.
- fixed panels for Rows `Caching` and `Upstream`
- added multi-tooltip for graphs with multi-values
- added link with Documentation

I have checked the changes that were made for the Grafana Dashboard for Kong 3, but that's not a direction I would recommend moving forward due to the following reasons:
- some rows have been changed to include a piece of documentation (`Request rate (Need to set config.status_code_metrics, it will cause performance impact`). I believe it is not user-friendly, so instead, I added a link with the documentation page for the Prometheus plugin.
- rows ordering has changed. I understand some metrics are optional, but when you think about Kong, the first things that pop into your head are requests and latency. I would not change the previous hierarchy and still leave Requests, Latency, and Bandwith as the first rows. I believe this is what most people would like to see when looking at the dashboard instead of Caching.

I look forward to your response, and I will commit my time to see this PR merged. 

Again, big thanks to the Kong team for making this happen.

Thank you,
Florin

**Comment by marinflorin** [comment]
Hey @hbagdi, @fffonion,

Any chance you can review this?

Thank you,
Florin

**Comment by marinflorin** [comment]
@hbagdi , @fffonion , please let me know if you need anything else for reviewing this PR. I can help with a test instance, Kong installation, dummy-app, etc. Just let me know how I can help so we can merge this :pray:

**Comment by hbagdi** [comment]
@fffonion Is there anyone from your team who can test this and report back?

**Comment by fffonion** [comment]
@ADD-SP could you give this a try locally? We can test it by having a granafa and prometheus instance locally, send some requests and validate every graph has stuff and make sure UI works ok.

**Review by fffonion — APPROVED** [review]

**Comment by fffonion** [comment]
Thank you @marinflorin for the contribution! Merging this in and also publish to grafana.com shortly.

**Comment by ADD-SP** [comment]
screencapture-3-112-40-119-3000-d-mY9p7dQmz-kong-official-2023-03-02-14_49_25

**Pull request merged**
