### PR TITLE
Update DEVELOPER.md

### PR DESCRIPTION
**Pull request by ios-shah**
### Summary

Added some brief information regarding Linux Environment Variables as it seems to be incomplete without this

### Full changelog

Environment variables are dynamic values that affect the programs or processes running on a server. They exist on every operating system, and their type may vary. Environment variables can be created, edited, saved and deleted.

Linux environment variables are placeholders for information stored within the system that passes data to programs launched in shells or sub-shells.

### Issues resolved

Fix #XXX

### CODE REVIEW

**Review by kikito — CHANGES_REQUESTED** [review]
Thank you for this suggestion, but we don't think it is needed. The `DEVELOPERS.md` document intented audience is someone already familiar with the concepts you added. The same way a cooking recipe does not explain how to bring water to boil, we should not be explaining basic concepts like environment variables there.

Your PR points however to something that is indeed missing from that doc, which is explaining the intended audience and prerequisites for a developer willing to install Kong. It could be at the very top of the file. "Being familiar with basic concepts like environment variables" would be on such list.

I'll leave this PR open for a while in case you want to transform to include that missing section instead.

**Comment by ios-shah** [comment]
Okk will make the further changes

**Comment by ios-shah** [comment]
I made the further changes do have a look at it!!

**Comment by ios-shah** [comment]
Hey do have a look at it and do tell me if you have any other suggestions..

**Comment by ios-shah** [comment]
Hey !! Do have a look

**Comment by kikito** [comment]
Hello, that is not what I was talking about. I suggest something like this:

```
## Intended audience and prerequisites

These instructions are intended for developers who want to start working with Kong.

As a prerequisite, the developer needs to be fluent in basic linux knowledge (like what an environment variable is, and what a linux distribution is) as well as familiar with virtualization software (VirtualBox and Docker)
```

**Pull request closed without merging**
