### PR TITLE
zipkin plugin

### LINKED ISSUE #1330: Integrate with Zipkin
Zipkin, https://github.com/openzipkin/zipkin,  is very useful for monitoring microservices.
However it requires every hop to be integrated.

### PR DESCRIPTION
**Pull request by james-callahan**
This PR adds the zipkin plugin to the Kong installation. The plugin itself is external, see https://github.com/Kong/kong-plugin-zipkin
The plugin has not tagged a release yet; when it does we should update the rockspec with the released version.

You may want to merge this on top of #3428 

### Full changelog

  - Add `ngx.ctx.KONG_BODY_FILTER_ENDED_AT`
  - Don't nil out `balancer_start`
  - Add zipkin plugin
  - Update nginx time cache in each phase

### Issues resolved

Fixes #1330

### CODE REVIEW

**Comment by coopr** [comment]
Docs need updating too - start here https://github.com/Kong/getkong.org/tree/docs-0.32-tracing

**Comment by james-callahan** [comment]
> We're missing the plugin order test - see https://github.com/Kong/kong/blob/master/spec/01-unit/014-plugins_order_spec.lua#L51

Added :)

**Comment by james-callahan** [comment]
Rebased on top of next now that #3428 is merged.

**Comment by thibaultcha** [comment]
Manually merged to next!

**Pull request closed without merging**
