### PR TITLE
fix(router) do not yield when incremental build

### PR DESCRIPTION
**Pull request by chronolaw**
### Summary

See FT-3291.

### CODE REVIEW

**Comment by bungle** [comment]
@chronolaw while this is a solution to fix the issue mentioned in FTI, I creates big concerns on incremental rebuild effects on latency with big data sets. We need to find a better solution. E.g. can the changes be prepared internally in router via some kind of `batch` functionality that then can be applied fast and atomically (non-yielding).

**Comment by chronolaw** [comment]
> @chronolaw while this is a solution to fix the issue mentioned in FTI, it creates big concerns on incremental rebuild effects on latency with large number of routes. We need to find a better solution. E.g. can the changes be prepared internally in router via some kind of `batch` functionality that then can be applied fast and atomically (non-yielding) inside the router.

Agree.

**Comment by dndx** [comment]
@bungle I agree we need some better way to do compare, but let's merge this PR first to stop the bleeding and let the testing continue. The current `master` is obviously broken because the yielding that broke atomicity.

**Review by dndx — APPROVED** [review]

**Comment by dndx** [comment]
Actually, second thought, I think we can keep the yields, but use the "rebuild_router_timer" should fix the issue of concurrent rebuilds. I will make a change for it.

**Comment by dndx** [comment]
We have a proper solution for this, and the issue does not affect CE. Closing this for now.

**Pull request closed without merging**
