### PR TITLE
release: 0.13.0

### PR DESCRIPTION
**Pull request by thibaultcha**
**Do not merge**

TODO:
- [x] Pull lua-resty-healthcheck version bump
- [x] Changelog
- [x] Upgrade path
- [x] Meta bumps

A few hotfixes cherry-picked from `master` since 0.13.0rc2: [0.13.0rc2...release/0.13.0](https://github.com/Kong/kong/compare/0.13.0rc2...release/0.13.0)

Rebase on top of next **before** merging into next.

### CODE REVIEW

**Comment by thibaultcha** [comment]
@hishamhm It seems like a16537c2e8cb63482e562c2c8e917284c68ecf35 forgot to update the `spec-old-api` version of the test

**Comment by hishamhm** [comment]
> It seems like a16537c forgot to update the spec-old-api version of the test

@thibaultcha fixed!

**Comment by thibaultcha** [comment]
For now, waiting on #3324 for the CI to pass on this branch.

**Comment by hishamhm** [comment]
:tada:

**Pull request closed without merging**
