### PR TITLE
fix(queues): best effort batching during shutdown

### PR DESCRIPTION
**Pull request by JensErat**
### Summary

During worker shutdown, batching was stopped entirely. Even if hundreds or thousands of queued items are waiting to be processed, no batches would have been built but hundreds or thousands of individual handler calls executed sequentially (potentially resulting in forced shutdown due to added up latency).

By not stopping batching entirely, but instead falling back to the minimal coalescing time already defined, we still allow best-effort batching, which will optimize shutdown queue flush behavior.

I added two commits: the first added a (failing) test to show batching is broken, the other one fixes batching again.

This is a pretty minimal change and rather optimization, not a bugfix. Do we need a changelog entry/... for this?

### Checklist

- [x] The Pull Request has tests
- [x] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

<sup>Jens Erat <jens.erat@[mercedes-benz.com](http://daimler.com/)>, Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

### CODE REVIEW

**Comment by hanshuebner** [comment]
Thank you for this fix - I would qualify it as a bug fix as in the scenarios where it helps, the non-batching behavior would be unexpected.  In any case, a CHANGELOG entry should be added.

**Review by hanshuebner — CHANGES_REQUESTED** [review]
Please add a CHANGELOG entry.  Looks good otherwise

**Comment by JensErat** [comment]
Rebased to get the "unreleased" section of the changelog and added the changelog entry. Should I squash the commits, or is this done when merging?

**Review by hanshuebner — APPROVED** [review]

**Review by hanshuebner — APPROVED** [review]

**Comment by hanshuebner** [comment]
@JensErat Sorry, there are new conflicts in your PR that need to be resolved.  Once done, I'll squash when I merge the PR.

**Comment by JensErat** [comment]
> @JensErat Sorry, there are new conflicts in your PR that need to be resolved. Once done, I'll squash when I merge the PR.

Done, luckily only the changelog was affected.

**Comment by hanshuebner** [comment]
Thanks.  We're working on changing how CHANGELOGs work to avoid such trivial conflicts in the future.  Will merge after tests have passed.

**Pull request merged**
