### PR TITLE
chore(deps) bump lyaml from 6.2.3 to 6.2.4

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Changelog:

- luke works with upgraded bootstrap luarocks version of require

(whatever that means)

### CODE REVIEW

**Comment by hishamhm** [comment]
It's just a build process fix on their end, there aren't even code changes in that tag. I don't think we're having any build problems with lyaml, so I guess the upgrade is not needed? ("if it ain't broke...")

**Comment by bungle** [comment]
@hishamhm, just keeping things up-to-date, and so that someone else will not propose this same later.

**Comment by thibaultcha** [comment]
Agreed with @bungle. However, let's merge this _after_ the 1.3.0 formal release, because @hishamhm also has a point :)

**Comment by hutchic** [comment]
This might require bumping it here https://github.com/Kong/kong-build-tools/blob/master/Makefile#L47 as well

**Comment by thibaultcha** [comment]
Manually merged to master.

**Pull request closed without merging**
