### PR TITLE
fix(sandbox) fix validate_function and validate

### PR DESCRIPTION
**Pull request by eskerda**
validator function was returning an incorrect error message on execution error.

### CODE REVIEW

**Review by gszr — APPROVED** [review]
💯

**Review by gszr — COMMENTED** [review]
Actually, @eskerda, could you base this one on master, so it goes into the patch release?

**Comment by eskerda** [comment]
> Actually, @eskerda, could you base this one on master, so it goes into the patch release?

sure!

**Comment by eskerda** [comment]
@gszr all set!

**Pull request merged**
