### PR TITLE
feat(vault): add file system (fs) vault

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Adds a file system vault.

### Checklist

- [ ] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

KAG-3736

### CODE REVIEW

**Comment by mheap** [comment]
@bungle News from the red cord. Could we hold off on this for a little while until we clarify requirements? They've shifted since you built this

**Comment by kikito** [comment]
Converting to draft, pending final requirements

**Comment by GGabriele** [comment]
@kikito @bungle is this going to be included in 3.7?

**Comment by bungle** [comment]
@GGabriele we never got final requirements. Should we go ahead and merge this?

**Comment by GGabriele** [comment]
That would be fine to me, but maybe @mheap knows more?

**Comment by mheap** [comment]
Let’s close until there’s a concrete need

**Pull request closed without merging**
