### PR TITLE
fix(pdk/log) ensure the `tries` table is encoded as JSON array instea…

### LINKED ISSUE #6390: JSON log with tries object or array
All the log plugins use `kong.log.serialize` method to generate log message and then use cjson to encode the message. 
The problem is the tries object in log message can be an json array or empty object:
```
    "tries": [
        {
            "state": "next",
            "code": 502,
            "ip": "127.0.0.1",
            "port": 8000
        },
        {
            "ip": "127.0.0.1",
            "port": 8000
        }
    ]
```
```
    "tries": {}
```
which make other languages very difficult to decode the log.

Use `setmetatable(tries, cjson.array_mt)` method can fixed this issue, but I don't know where this code should go.

I create a PR #6386  that add this lines into `kong/pdk/log.lua`,  but a better idea is move it to `balancer phase`. Maybe someone could do this.

### PR DESCRIPTION
**Pull request by dndx**
…d of

object when empty. fixes #6390

### CODE REVIEW

**Review by Tieske — APPROVED** [review]
👍

**Comment by Tieske** [comment]
Approved, awaiting CI

**Review by bungle — APPROVED** [review]

**Comment by dndx** [comment]
Test failure unrelated to this change, @gszr is working on a fix.

**Comment by dndx** [comment]
Merging for now, @gszr is working on fixing the smoke test and it is not a blocker.

**Pull request merged**
