### PR TITLE
tests(migrations): add 3.1 migrations spec

### PR DESCRIPTION
**Pull request by attenuation**
### Summary
add 3.1 migrations spec

### Issue reference
#9430

### CODE REVIEW

**Comment by fffonion** [comment]
could you rebase your PR on branch of this one https://github.com/Kong/kong/pull/9487? so we can actually run CI

**Comment by chronolaw** [comment]
Should we change the title to `tests(...)`?

**Comment by chronolaw** [comment]
Could you add some explain about the close?

**Comment by attenuation** [comment]
@chronolaw https://github.com/Kong/kong/pull/9565 for change base branch to hans

**Pull request closed without merging**
